'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Kayttaja

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''ReqValtxtKayttajatunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValtxtKayttajatunnus As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtKayttajatunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKayttajatunnus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''regSahkoposti control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regSahkoposti As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''txtSahkoposti control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSahkoposti As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtEtunimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEtunimi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSukunimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSukunimi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValtxtSalasana control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValtxtSalasana As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtSalasana control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSalasana As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
End Class
