'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Kayttajat

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''ddRooli control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddRooli As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btLisaaValitutKayttajatRooliin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btLisaaValitutKayttajatRooliin As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPoistaValitutKayttajatRoolista control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPoistaValitutKayttajatRoolista As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ddRyhma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddRyhma As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btLisaaValitutKayttajatRyhmaan control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btLisaaValitutKayttajatRyhmaan As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPoistaValitutKayttajatRyhmasta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPoistaValitutKayttajatRyhmasta As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btLisaaKayttaja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btLisaaKayttaja As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''gwTulokset control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gwTulokset As Global.System.Web.UI.WebControls.GridView
End Class
