//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace appIFSIntegraatio.IFS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.LobServices.OracleDB/2007/03/IFSINFO/View/C_CONCORDIA_PAYMENTS")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.OracleDB/2007/03/IFSINFO/View/C_CONCORDIA_PAYMENTS", IsNullable=false)]
    public partial class SelectResponse {
        
        private SelectResponseSelectResult[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SelectResult")]
        public SelectResponseSelectResult[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.LobServices.OracleDB/2007/03/IFSINFO/View/C_CONCORDIA_PAYMENTS")]
    public partial class SelectResponseSelectResult {
        
        private SelectResponseSelectResultC_CONCORDIA_PAYMENTSRECORDSELECT[] c_CONCORDIA_PAYMENTSRECORDSELECTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("C_CONCORDIA_PAYMENTSRECORDSELECT")]
        public SelectResponseSelectResultC_CONCORDIA_PAYMENTSRECORDSELECT[] C_CONCORDIA_PAYMENTSRECORDSELECT {
            get {
                return this.c_CONCORDIA_PAYMENTSRECORDSELECTField;
            }
            set {
                this.c_CONCORDIA_PAYMENTSRECORDSELECTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.LobServices.OracleDB/2007/03/IFSINFO/View/C_CONCORDIA_PAYMENTS")]
    public partial class SelectResponseSelectResultC_CONCORDIA_PAYMENTSRECORDSELECT {
        
        private string sEQUENCEField;
        
        private string pAYMENT_REFERENCEField;
        
        private string pAYMENT_DATEField;
        
        private string iNVOICE_NOField;
        
        private string iFS_INVOICE_NOField;
        
        private string nAMEField;
        
        private string aMOUNTField;
        
        /// <remarks/>
        public string SEQUENCE {
            get {
                return this.sEQUENCEField;
            }
            set {
                this.sEQUENCEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYMENT_REFERENCE {
            get {
                return this.pAYMENT_REFERENCEField;
            }
            set {
                this.pAYMENT_REFERENCEField = value;
            }
        }
        
        /// <remarks/>
        public string PAYMENT_DATE {
            get {
                return this.pAYMENT_DATEField;
            }
            set {
                this.pAYMENT_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string INVOICE_NO {
            get {
                return this.iNVOICE_NOField;
            }
            set {
                this.iNVOICE_NOField = value;
            }
        }
        
        /// <remarks/>
        public string IFS_INVOICE_NO {
            get {
                return this.iFS_INVOICE_NOField;
            }
            set {
                this.iFS_INVOICE_NOField = value;
            }
        }
        
        /// <remarks/>
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
            }
        }
        
        /// <remarks/>
        public string AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
            }
        }
    }
}
