'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MaksuaineistojenTiedot

    '''<summary>
    '''Tyokalut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

    '''<summary>
    '''Haku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

    '''<summary>
    '''hlTakaisin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTakaisin As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btnTeeEsikatseluaineisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTeeEsikatseluaineisto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTeeMaksuaineisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTeeMaksuaineisto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddKORKorvaustyyppiId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddKORKorvaustyyppiId As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddKORKorvauslaskelmaStatusId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddKORKorvauslaskelmaStatusId As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTiedot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gwTulokset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gwTulokset As Global.System.Web.UI.WebControls.GridView
End Class
