'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace RaporttiKontrollit
    
    Partial Public Class Vuokrat
        
        '''<summary>
        '''SopimustyyppiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SopimustyyppiId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''KorvaustyyppiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KorvaustyyppiId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''MaksukuukausiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MaksukuukausiId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''reportContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reportContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lstReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstReport As Global.System.Web.UI.WebControls.ListView
    End Class
End Namespace
