'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AktiviteetinMuokkaus

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''hdnAId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdnAId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''hdnSId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdnSId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''phYksiSopimus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phYksiSopimus As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''lblAKSopimusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAKSopimusId As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''phMontaSopimusta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phMontaSopimusta As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''lblMontaSopimusta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMontaSopimusta As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''phPaivitystiedot control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phPaivitystiedot As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''lblAKPaivitetty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAKPaivitetty As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblAKPaivittaja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAKPaivittaja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblAKLuotu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAKLuotu As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblAKLuoja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAKLuoja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ddAKTahoId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddAKTahoId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddAKKontaktoijaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddAKKontaktoijaId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''custvalAKYhteystapaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents custvalAKYhteystapaId As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''ddAKYhteystapaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddAKYhteystapaId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddAKAktiviteetinLajiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddAKAktiviteetinLajiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''comAKPaivamaara2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents comAKPaivamaara2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''comAKPaivamaara control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents comAKPaivamaara As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtAKPaivamaara control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtAKPaivamaara As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''imgAKPaivamaara control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgAKPaivamaara As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''calAKPaivamaara control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calAKPaivamaara As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''comAKSeuraavaYhteyspaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents comAKSeuraavaYhteyspaiva As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtAKSeuraavaYhteyspaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtAKSeuraavaYhteyspaiva As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''imgAKSeuraavaYhteyspaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgAKSeuraavaYhteyspaiva As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''calAKSeuraavaYhteyspaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calAKSeuraavaYhteyspaiva As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''txtAKKuvaus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtAKKuvaus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valAKStatusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valAKStatusId As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ddAKStatusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddAKStatusId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnPeruuta As Global.System.Web.UI.WebControls.Button
End Class
