ALTER TABLE Tiedosto ADD TIEMFilesVault UNIQUEIDENTIFIER NULL
GO

ALTER TABLE Tiedosto ADD TIEMFilesType INT NOT NULL DEFAULT(0)
GO

ALTER TABLE Tiedosto ADD TIEMFilesId INT NULL
GO

ALTER TABLE Tiedosto ADD TIEMFilesObject UNIQUEIDENTIFIER NULL
GO