'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HenkilonMuokkaus
    
    '''<summary>
    '''Tyokalut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut
    
    '''<summary>
    '''Haku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue
    
    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''phPaivitystiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPaivitystiedot As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblTAHPaivitetty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTAHPaivitetty As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTAHPaivittaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTAHPaivittaja As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTAHLuotu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTAHLuotu As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTAHLuoja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTAHLuoja As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAsiakastyyppi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAsiakastyyppi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ifpTAHEtunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHEtunimi As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHEtunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHEtunimi As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtTAHEtunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHEtunimi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHSukunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHSukunimi As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHSukunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHSukunimi As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtTAHSukunimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHSukunimi As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHNimitarkenne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHNimitarkenne As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''txtTAHNimitarkenne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHNimitarkenne As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHPostitusosoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHPostitusosoite As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHPostitusosoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHPostitusosoite As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtTAHPostitusosoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHPostitusosoite As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHPostituspostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHPostituspostinro As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHPostituspostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHPostituspostinro As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ComValTAHPostituspostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComValTAHPostituspostinro As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtTAHPostituspostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHPostituspostinro As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnHaePostitoimipaikka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHaePostitoimipaikka As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ifpTAHPostituspostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHPostituspostitmp As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHPostituspostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHPostituspostitmp As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtTAHPostituspostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHPostituspostitmp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHKuntaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHKuntaId As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''ddTAHKuntaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTAHKuntaId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ifpTAHMaaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHMaaId As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''ddTAHMaaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTAHMaaId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ifpTAHPuhelin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHPuhelin As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''rvtxtTAHPuhelin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtTAHPuhelin As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtTAHPuhelin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHPuhelin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHEmail As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''txtTAHEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHTilinumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHTilinumero As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''CusValTAHTilinumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CusValTAHTilinumero As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''txtTAHTilinumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHTilinumero As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHBicKoodiId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHBicKoodiId As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''CusValBic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CusValBic As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''ddTAHBicKoodiId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTAHBicKoodiId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ifpTAHBic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHBic As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''txtTAHBic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHBic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ifpTAHInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifpTAHInfo As Global.appSopimusrekisteri.Infopallura
    
    '''<summary>
    '''txtTAHInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTAHInfo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btTallenna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btPeruuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
End Class
