'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SopimusarkistoViews
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName:="SopimusarkistoViews.ViewsSoap")>  _
    Public Interface ViewsSoap
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetView", ReplyAction:="*")>  _
        Function GetView(ByVal request As SopimusarkistoViews.GetViewRequest) As SopimusarkistoViews.GetViewResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetView", ReplyAction:="*")>  _
        Function GetViewAsync(ByVal request As SopimusarkistoViews.GetViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewHtml", ReplyAction:="*")>  _
        Function GetViewHtml(ByVal request As SopimusarkistoViews.GetViewHtmlRequest) As SopimusarkistoViews.GetViewHtmlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewHtml", ReplyAction:="*")>  _
        Function GetViewHtmlAsync(ByVal request As SopimusarkistoViews.GetViewHtmlRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewHtmlResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/DeleteView", ReplyAction:="*")>  _
        Function DeleteView(ByVal request As SopimusarkistoViews.DeleteViewRequest) As SopimusarkistoViews.DeleteViewResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/DeleteView", ReplyAction:="*")>  _
        Function DeleteViewAsync(ByVal request As SopimusarkistoViews.DeleteViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.DeleteViewResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/AddView", ReplyAction:="*")>  _
        Function AddView(ByVal request As SopimusarkistoViews.AddViewRequest) As SopimusarkistoViews.AddViewResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/AddView", ReplyAction:="*")>  _
        Function AddViewAsync(ByVal request As SopimusarkistoViews.AddViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.AddViewResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewCollection", ReplyAction:="*")>  _
        Function GetViewCollection(ByVal request As SopimusarkistoViews.GetViewCollectionRequest) As SopimusarkistoViews.GetViewCollectionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewCollection", ReplyAction:="*")>  _
        Function GetViewCollectionAsync(ByVal request As SopimusarkistoViews.GetViewCollectionRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewCollectionResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateView", ReplyAction:="*")>  _
        Function UpdateView(ByVal request As SopimusarkistoViews.UpdateViewRequest) As SopimusarkistoViews.UpdateViewResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateView", ReplyAction:="*")>  _
        Function UpdateViewAsync(ByVal request As SopimusarkistoViews.UpdateViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml", ReplyAction:="*")>  _
        Function UpdateViewHtml(ByVal request As SopimusarkistoViews.UpdateViewHtmlRequest) As SopimusarkistoViews.UpdateViewHtmlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml", ReplyAction:="*")>  _
        Function UpdateViewHtmlAsync(ByVal request As SopimusarkistoViews.UpdateViewHtmlRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtmlResponse)
        
        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml2", ReplyAction:="*")>  _
        Function UpdateViewHtml2(ByVal request As SopimusarkistoViews.UpdateViewHtml2Request) As SopimusarkistoViews.UpdateViewHtml2Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml2", ReplyAction:="*")>  _
        Function UpdateViewHtml2Async(ByVal request As SopimusarkistoViews.UpdateViewHtml2Request) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtml2Response)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetViewResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetViewResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetViewResult = GetViewResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewHtmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewHtml", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewHtmlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewHtmlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewHtmlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewHtmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewHtmlResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewHtmlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewHtmlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewHtmlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetViewHtmlResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetViewHtmlResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetViewHtmlResult = GetViewHtmlResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeleteViewRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeleteView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.DeleteViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.DeleteViewRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class DeleteViewRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeleteViewResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeleteViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.DeleteViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.DeleteViewResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class DeleteViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddViewRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.AddViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.AddViewRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class AddViewRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public viewFields As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public query As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public rowLimit As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public type As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public makeViewDefault As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewFields As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal type As String, ByVal makeViewDefault As Boolean)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
            Me.viewFields = viewFields
            Me.query = query
            Me.rowLimit = rowLimit
            Me.type = type
            Me.makeViewDefault = makeViewDefault
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddViewResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.AddViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.AddViewResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class AddViewResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddViewResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddViewResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.AddViewResult = AddViewResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewCollectionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewCollection", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewCollectionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewCollectionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewCollectionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String)
            MyBase.New
            Me.listName = listName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetViewCollectionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewCollectionResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.GetViewCollectionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.GetViewCollectionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class GetViewCollectionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetViewCollectionResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetViewCollectionResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.GetViewCollectionResult = GetViewCollectionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public viewProperties As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public query As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public viewFields As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public aggregations As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public formats As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public rowLimit As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateViewResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateViewResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.UpdateViewResult = UpdateViewResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewHtmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewHtmlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewHtmlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewHtmlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public viewProperties As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public toolbar As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public viewHeader As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public viewBody As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public viewFooter As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public viewEmpty As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public rowLimitExceeded As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public query As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public viewFields As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public aggregations As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public formats As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public rowLimit As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.toolbar = toolbar
            Me.viewHeader = viewHeader
            Me.viewBody = viewBody
            Me.viewFooter = viewFooter
            Me.viewEmpty = viewEmpty
            Me.rowLimitExceeded = rowLimitExceeded
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewHtmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtmlResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewHtmlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewHtmlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewHtmlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateViewHtmlResult As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateViewHtmlResult As System.Xml.Linq.XElement)
            MyBase.New
            Me.UpdateViewHtmlResult = UpdateViewHtmlResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewHtml2Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml2", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewHtml2RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewHtml2RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewHtml2RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public listName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public viewName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public viewProperties As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public toolbar As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public viewHeader As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public viewBody As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public viewFooter As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public viewEmpty As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public rowLimitExceeded As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public query As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public viewFields As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public aggregations As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public formats As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public rowLimit As System.Xml.Linq.XElement
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public openApplicationExtension As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal openApplicationExtension As String)
            MyBase.New
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.toolbar = toolbar
            Me.viewHeader = viewHeader
            Me.viewBody = viewBody
            Me.viewFooter = viewFooter
            Me.viewEmpty = viewEmpty
            Me.rowLimitExceeded = rowLimitExceeded
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
            Me.openApplicationExtension = openApplicationExtension
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateViewHtml2Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml2Response", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)>  _
        Public Body As SopimusarkistoViews.UpdateViewHtml2ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SopimusarkistoViews.UpdateViewHtml2ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")>  _
    Partial Public Class UpdateViewHtml2ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateViewHtml2Result As System.Xml.Linq.XElement
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateViewHtml2Result As System.Xml.Linq.XElement)
            MyBase.New
            Me.UpdateViewHtml2Result = UpdateViewHtml2Result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ViewsSoapChannel
        Inherits SopimusarkistoViews.ViewsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ViewsSoapClient
        Inherits System.ServiceModel.ClientBase(Of SopimusarkistoViews.ViewsSoap)
        Implements SopimusarkistoViews.ViewsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetView(ByVal request As SopimusarkistoViews.GetViewRequest) As SopimusarkistoViews.GetViewResponse Implements SopimusarkistoViews.ViewsSoap.GetView
            Return MyBase.Channel.GetView(request)
        End Function
        
        Public Function GetView(ByVal listName As String, ByVal viewName As String) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.GetViewRequest = New SopimusarkistoViews.GetViewRequest()
            inValue.Body = New SopimusarkistoViews.GetViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As SopimusarkistoViews.GetViewResponse = CType(Me,SopimusarkistoViews.ViewsSoap).GetView(inValue)
            Return retVal.Body.GetViewResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetViewAsync(ByVal request As SopimusarkistoViews.GetViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewResponse) Implements SopimusarkistoViews.ViewsSoap.GetViewAsync
            Return MyBase.Channel.GetViewAsync(request)
        End Function
        
        Public Function GetViewAsync(ByVal listName As String, ByVal viewName As String) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewResponse)
            Dim inValue As SopimusarkistoViews.GetViewRequest = New SopimusarkistoViews.GetViewRequest()
            inValue.Body = New SopimusarkistoViews.GetViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Return CType(Me,SopimusarkistoViews.ViewsSoap).GetViewAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetViewHtml(ByVal request As SopimusarkistoViews.GetViewHtmlRequest) As SopimusarkistoViews.GetViewHtmlResponse Implements SopimusarkistoViews.ViewsSoap.GetViewHtml
            Return MyBase.Channel.GetViewHtml(request)
        End Function
        
        Public Function GetViewHtml(ByVal listName As String, ByVal viewName As String) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.GetViewHtmlRequest = New SopimusarkistoViews.GetViewHtmlRequest()
            inValue.Body = New SopimusarkistoViews.GetViewHtmlRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As SopimusarkistoViews.GetViewHtmlResponse = CType(Me,SopimusarkistoViews.ViewsSoap).GetViewHtml(inValue)
            Return retVal.Body.GetViewHtmlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetViewHtmlAsync(ByVal request As SopimusarkistoViews.GetViewHtmlRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewHtmlResponse) Implements SopimusarkistoViews.ViewsSoap.GetViewHtmlAsync
            Return MyBase.Channel.GetViewHtmlAsync(request)
        End Function
        
        Public Function GetViewHtmlAsync(ByVal listName As String, ByVal viewName As String) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewHtmlResponse)
            Dim inValue As SopimusarkistoViews.GetViewHtmlRequest = New SopimusarkistoViews.GetViewHtmlRequest()
            inValue.Body = New SopimusarkistoViews.GetViewHtmlRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Return CType(Me,SopimusarkistoViews.ViewsSoap).GetViewHtmlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_DeleteView(ByVal request As SopimusarkistoViews.DeleteViewRequest) As SopimusarkistoViews.DeleteViewResponse Implements SopimusarkistoViews.ViewsSoap.DeleteView
            Return MyBase.Channel.DeleteView(request)
        End Function
        
        Public Sub DeleteView(ByVal listName As String, ByVal viewName As String)
            Dim inValue As SopimusarkistoViews.DeleteViewRequest = New SopimusarkistoViews.DeleteViewRequest()
            inValue.Body = New SopimusarkistoViews.DeleteViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As SopimusarkistoViews.DeleteViewResponse = CType(Me,SopimusarkistoViews.ViewsSoap).DeleteView(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_DeleteViewAsync(ByVal request As SopimusarkistoViews.DeleteViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.DeleteViewResponse) Implements SopimusarkistoViews.ViewsSoap.DeleteViewAsync
            Return MyBase.Channel.DeleteViewAsync(request)
        End Function
        
        Public Function DeleteViewAsync(ByVal listName As String, ByVal viewName As String) As System.Threading.Tasks.Task(Of SopimusarkistoViews.DeleteViewResponse)
            Dim inValue As SopimusarkistoViews.DeleteViewRequest = New SopimusarkistoViews.DeleteViewRequest()
            inValue.Body = New SopimusarkistoViews.DeleteViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Return CType(Me,SopimusarkistoViews.ViewsSoap).DeleteViewAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_AddView(ByVal request As SopimusarkistoViews.AddViewRequest) As SopimusarkistoViews.AddViewResponse Implements SopimusarkistoViews.ViewsSoap.AddView
            Return MyBase.Channel.AddView(request)
        End Function
        
        Public Function AddView(ByVal listName As String, ByVal viewName As String, ByVal viewFields As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal type As String, ByVal makeViewDefault As Boolean) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.AddViewRequest = New SopimusarkistoViews.AddViewRequest()
            inValue.Body = New SopimusarkistoViews.AddViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewFields = viewFields
            inValue.Body.query = query
            inValue.Body.rowLimit = rowLimit
            inValue.Body.type = type
            inValue.Body.makeViewDefault = makeViewDefault
            Dim retVal As SopimusarkistoViews.AddViewResponse = CType(Me,SopimusarkistoViews.ViewsSoap).AddView(inValue)
            Return retVal.Body.AddViewResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_AddViewAsync(ByVal request As SopimusarkistoViews.AddViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.AddViewResponse) Implements SopimusarkistoViews.ViewsSoap.AddViewAsync
            Return MyBase.Channel.AddViewAsync(request)
        End Function
        
        Public Function AddViewAsync(ByVal listName As String, ByVal viewName As String, ByVal viewFields As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal type As String, ByVal makeViewDefault As Boolean) As System.Threading.Tasks.Task(Of SopimusarkistoViews.AddViewResponse)
            Dim inValue As SopimusarkistoViews.AddViewRequest = New SopimusarkistoViews.AddViewRequest()
            inValue.Body = New SopimusarkistoViews.AddViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewFields = viewFields
            inValue.Body.query = query
            inValue.Body.rowLimit = rowLimit
            inValue.Body.type = type
            inValue.Body.makeViewDefault = makeViewDefault
            Return CType(Me,SopimusarkistoViews.ViewsSoap).AddViewAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetViewCollection(ByVal request As SopimusarkistoViews.GetViewCollectionRequest) As SopimusarkistoViews.GetViewCollectionResponse Implements SopimusarkistoViews.ViewsSoap.GetViewCollection
            Return MyBase.Channel.GetViewCollection(request)
        End Function
        
        Public Function GetViewCollection(ByVal listName As String) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.GetViewCollectionRequest = New SopimusarkistoViews.GetViewCollectionRequest()
            inValue.Body = New SopimusarkistoViews.GetViewCollectionRequestBody()
            inValue.Body.listName = listName
            Dim retVal As SopimusarkistoViews.GetViewCollectionResponse = CType(Me,SopimusarkistoViews.ViewsSoap).GetViewCollection(inValue)
            Return retVal.Body.GetViewCollectionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_GetViewCollectionAsync(ByVal request As SopimusarkistoViews.GetViewCollectionRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewCollectionResponse) Implements SopimusarkistoViews.ViewsSoap.GetViewCollectionAsync
            Return MyBase.Channel.GetViewCollectionAsync(request)
        End Function
        
        Public Function GetViewCollectionAsync(ByVal listName As String) As System.Threading.Tasks.Task(Of SopimusarkistoViews.GetViewCollectionResponse)
            Dim inValue As SopimusarkistoViews.GetViewCollectionRequest = New SopimusarkistoViews.GetViewCollectionRequest()
            inValue.Body = New SopimusarkistoViews.GetViewCollectionRequestBody()
            inValue.Body.listName = listName
            Return CType(Me,SopimusarkistoViews.ViewsSoap).GetViewCollectionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateView(ByVal request As SopimusarkistoViews.UpdateViewRequest) As SopimusarkistoViews.UpdateViewResponse Implements SopimusarkistoViews.ViewsSoap.UpdateView
            Return MyBase.Channel.UpdateView(request)
        End Function
        
        Public Function UpdateView(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.UpdateViewRequest = New SopimusarkistoViews.UpdateViewRequest()
            inValue.Body = New SopimusarkistoViews.UpdateViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Dim retVal As SopimusarkistoViews.UpdateViewResponse = CType(Me,SopimusarkistoViews.ViewsSoap).UpdateView(inValue)
            Return retVal.Body.UpdateViewResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateViewAsync(ByVal request As SopimusarkistoViews.UpdateViewRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewResponse) Implements SopimusarkistoViews.ViewsSoap.UpdateViewAsync
            Return MyBase.Channel.UpdateViewAsync(request)
        End Function
        
        Public Function UpdateViewAsync(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewResponse)
            Dim inValue As SopimusarkistoViews.UpdateViewRequest = New SopimusarkistoViews.UpdateViewRequest()
            inValue.Body = New SopimusarkistoViews.UpdateViewRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Return CType(Me,SopimusarkistoViews.ViewsSoap).UpdateViewAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateViewHtml(ByVal request As SopimusarkistoViews.UpdateViewHtmlRequest) As SopimusarkistoViews.UpdateViewHtmlResponse Implements SopimusarkistoViews.ViewsSoap.UpdateViewHtml
            Return MyBase.Channel.UpdateViewHtml(request)
        End Function
        
        Public Function UpdateViewHtml(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.UpdateViewHtmlRequest = New SopimusarkistoViews.UpdateViewHtmlRequest()
            inValue.Body = New SopimusarkistoViews.UpdateViewHtmlRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Dim retVal As SopimusarkistoViews.UpdateViewHtmlResponse = CType(Me,SopimusarkistoViews.ViewsSoap).UpdateViewHtml(inValue)
            Return retVal.Body.UpdateViewHtmlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateViewHtmlAsync(ByVal request As SopimusarkistoViews.UpdateViewHtmlRequest) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtmlResponse) Implements SopimusarkistoViews.ViewsSoap.UpdateViewHtmlAsync
            Return MyBase.Channel.UpdateViewHtmlAsync(request)
        End Function
        
        Public Function UpdateViewHtmlAsync(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtmlResponse)
            Dim inValue As SopimusarkistoViews.UpdateViewHtmlRequest = New SopimusarkistoViews.UpdateViewHtmlRequest()
            inValue.Body = New SopimusarkistoViews.UpdateViewHtmlRequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Return CType(Me,SopimusarkistoViews.ViewsSoap).UpdateViewHtmlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateViewHtml2(ByVal request As SopimusarkistoViews.UpdateViewHtml2Request) As SopimusarkistoViews.UpdateViewHtml2Response Implements SopimusarkistoViews.ViewsSoap.UpdateViewHtml2
            Return MyBase.Channel.UpdateViewHtml2(request)
        End Function
        
        Public Function UpdateViewHtml2(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal openApplicationExtension As String) As System.Xml.Linq.XElement
            Dim inValue As SopimusarkistoViews.UpdateViewHtml2Request = New SopimusarkistoViews.UpdateViewHtml2Request()
            inValue.Body = New SopimusarkistoViews.UpdateViewHtml2RequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            inValue.Body.openApplicationExtension = openApplicationExtension
            Dim retVal As SopimusarkistoViews.UpdateViewHtml2Response = CType(Me,SopimusarkistoViews.ViewsSoap).UpdateViewHtml2(inValue)
            Return retVal.Body.UpdateViewHtml2Result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SopimusarkistoViews_ViewsSoap_UpdateViewHtml2Async(ByVal request As SopimusarkistoViews.UpdateViewHtml2Request) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtml2Response) Implements SopimusarkistoViews.ViewsSoap.UpdateViewHtml2Async
            Return MyBase.Channel.UpdateViewHtml2Async(request)
        End Function
        
        Public Function UpdateViewHtml2Async(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal openApplicationExtension As String) As System.Threading.Tasks.Task(Of SopimusarkistoViews.UpdateViewHtml2Response)
            Dim inValue As SopimusarkistoViews.UpdateViewHtml2Request = New SopimusarkistoViews.UpdateViewHtml2Request()
            inValue.Body = New SopimusarkistoViews.UpdateViewHtml2RequestBody()
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            inValue.Body.openApplicationExtension = openApplicationExtension
            Return CType(Me,SopimusarkistoViews.ViewsSoap).UpdateViewHtml2Async(inValue)
        End Function
    End Class
End Namespace
