'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Haku

    '''<summary>
    '''txtHaku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHaku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHae As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rbTontti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbTontti As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSopimus As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''imgNuoli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNuoli As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hlTarkennettuhaku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTarkennettuhaku As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlTontti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTontti As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlSopimus As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblLkm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLkm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlLisaHakutulokset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlLisaHakutulokset As Global.System.Web.UI.WebControls.HyperLink
End Class
