'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class perusnaytto_sopimus

    '''<summary>
    '''HenkiloTyokalut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HenkiloTyokalut1 As Global.appFortumMalli.HenkiloTyokalut

    '''<summary>
    '''Haku1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku1 As Global.appFortumMalli.Haku

    '''<summary>
    '''Perustiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Perustiedot As Global.appFortumMalli.perustiedot_sopimus

    '''<summary>
    '''kiinteistoPerustiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kiinteistoPerustiedot As Global.appFortumMalli.kiinteistot

    '''<summary>
    '''muuntamot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents muuntamot As Global.appFortumMalli.muuntajatiedot

    '''<summary>
    '''yhteystiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yhteystiedot As Global.appFortumMalli.yhteystiedot

    '''<summary>
    '''korvaus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents korvaus As Global.appFortumMalli.korvaus

    '''<summary>
    '''tiedosto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tiedosto As Global.appFortumMalli.tiedosto

    '''<summary>
    '''aktiviteetti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aktiviteetti As Global.appFortumMalli.aktiviteetti

    '''<summary>
    '''maksu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maksu As Global.appFortumMalli.maksu
End Class
