'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class poimintajoukko

    '''<summary>
    '''HenkiloTyokalut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HenkiloTyokalut1 As Global.appFortumMalli.HenkiloTyokalut

    '''<summary>
    '''Haku1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku1 As Global.appFortumMalli.Haku

    '''<summary>
    '''btnUusiPoiminta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUusiPoiminta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlSopimus As Global.System.Web.UI.WebControls.HyperLink
End Class
