'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class poimintalomake

    '''<summary>
    '''HenkiloTyokalut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HenkiloTyokalut1 As Global.appFortumMalli.HenkiloTyokalut

    '''<summary>
    '''Haku1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku1 As Global.appFortumMalli.Haku

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''cpeKiinteisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeKiinteisto As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''imgKiinteisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgKiinteisto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlKiinteisto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlKiinteisto As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlKiinteistonKunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKiinteistonKunta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKiinteistonKyla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKiinteistonKyla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKiinteistonPostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKiinteistonPostinro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cpeSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeSopimus As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''imgSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSopimus As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSopimus As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlSopimuksenTyyppi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSopimuksenTyyppi As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSopimusAlkupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopimusAlkupvm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgKAMAlkupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgKAMAlkupvm As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtSopimusLoppupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopimusLoppupvm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ddlKesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKesto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMuutunniste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuutunniste As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPCS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSopHetkenIndeksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopHetkenIndeksi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPoimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPoimi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPeru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeru As Global.System.Web.UI.WebControls.Button
End Class
