'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class sopimus_edit

    '''<summary>
    '''HenkiloTyokalut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HenkiloTyokalut1 As Global.appFortumMalli.HenkiloTyokalut

    '''<summary>
    '''Haku1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku1 As Global.appFortumMalli.Haku

    '''<summary>
    '''ddlYhtio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlYhtio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtSopijanimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopijanimi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTonttinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTonttinro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTonttiNimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTonttiNimi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKatuosoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKatuosoite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostinro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostitmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTonttiKunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTonttiKunta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTonttiKyla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTonttiKyla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKiinteistoTunnus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKiinteistoTunnus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSopimusAlkupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopimusAlkupvm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgKAMAlkupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgKAMAlkupvm As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtSopimusLoppupvm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSopimusLoppupvm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img1 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''ddlKesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKesto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMuutunniste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuutunniste As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPCS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSophetkenIndeksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSophetkenIndeksi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMuuntamoTunnus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuuntamoTunnus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMuuntamoNimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuuntamoNimi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMuuntamoOsoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuuntamoOsoite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMuuntamoPostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuuntamoPostitmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMuuntamoPintaala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMuuntamoPintaala As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOmistajanimi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOmistajanimi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOmistajaOsoite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOmistajaOsoite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtomistajaPostinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtomistajaPostinro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOmistajaPostitmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOmistajaPostitmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtomistajaPuh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtomistajaPuh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOmistajasposti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOmistajasposti As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOmistajaTilinro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOmistajaTilinro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnJatka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJatka As Global.System.Web.UI.WebControls.Button
End Class
