'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PoimintaTyokalut

  '''<summary>
  '''hlSarakevalintaSopimus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hlSarakevalintaSopimus As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''hlSarakevalintaKiinteisto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hlSarakevalintaKiinteisto As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''hlSarakevalintaTaho control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hlSarakevalintaTaho As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''lbNollaaSarakkeet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbNollaaSarakkeet As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''phJoukkolisays control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phJoukkolisays As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''hlLisaaAktiviteetti control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hlLisaaAktiviteetti As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''HyperLink1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''HyperLink2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HyperLink2 As Global.System.Web.UI.WebControls.HyperLink
End Class
