'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Muokkaa1

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''hdnId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdnId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''lblPaivitetty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPaivitetty As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblPaivittaja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPaivittaja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblLuotu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblLuotu As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblLuoja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblLuoja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ReqValIndeksityyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValIndeksityyppiId As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ddIndeksityyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddIndeksityyppiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqValVuosi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValVuosi As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ComValVuosi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValVuosi As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtVuosi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtVuosi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ReqValKuukausi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValKuukausi As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ddKuukausiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKuukausiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqValArvo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValArvo As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ComValArvo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValArvo As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtArvo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtArvo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
End Class
