'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class KorvaushinnastonMuokkaus

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''phPaivitystiedot control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phPaivitystiedot As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''lblKHIPaivitetty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKHIPaivitetty As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblKHIPaivittaja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKHIPaivittaja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblKHILuotu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKHILuotu As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblKHILuoja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKHILuoja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtKHIKorvauslaji control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIKorvauslaji As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtKHIKuvaus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIKuvaus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ddKHISopimustyyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHISopimustyyppiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddKHIYksikkoId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIYksikkoId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''cmpKHIYksikkkohinta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHIYksikkkohinta As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHIYksikkkohinta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIYksikkkohinta As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtKHIYksikkohinnanTarkenne control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIYksikkohinnanTarkenne As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ddKHIMetsatyyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIMetsatyyppiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddKHIPuustolajiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIPuustolajiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddKHIHinnastoKategoriaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIHinnastoKategoriaId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddKHIHinnastoAlakategoriaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIHinnastoAlakategoriaId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txtKHIArvonPeruste control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIArvonPeruste As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ddKHIMaksuAlueId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKHIMaksuAlueId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''cmpKHIPuustonIka control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHIPuustonIka As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHIPuustonIka control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIPuustonIka As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmpKHITaimistonValtapituus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHITaimistonValtapituus As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHITaimistonValtapituus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHITaimistonValtapituus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmpKHITiheyskerroin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHITiheyskerroin As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHITiheyskerroin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHITiheyskerroin As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmpKHIAlkuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHIAlkuPvm As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHIAlkuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIAlkuPvm As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''imgKHIAlkuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgKHIAlkuPvm As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''calKHIAlkuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calKHIAlkuPvm As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''cmpKHILoppuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpKHILoppuPvm As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtKHILoppuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHILoppuPvm As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''imgKHILoppuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgKHILoppuPvm As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''calKHILoppuPvm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calKHILoppuPvm As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''cbKHIAktiivinen control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cbKHIAktiivinen As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''txtKHIInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtKHIInfo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
End Class
