'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aktiviteetti
    Public Property AKId As Integer
    Public Property AKTahoId As Nullable(Of Integer)
    Public Property AKTSopimusId As Nullable(Of Integer)
    Public Property AKYhteystapaId As Nullable(Of Integer)
    Public Property AKPaivamaara As Nullable(Of Date)
    Public Property AKKuvaus As String
    Public Property AKAktiviteetinLajiId As Nullable(Of Integer)
    Public Property AKSeuraavaYhteyspaiva As Nullable(Of Date)
    Public Property AKStatusId As Nullable(Of Integer)
    Public Property AKLiitetiedostoPolku As String
    Public Property AKLuotu As Nullable(Of Date)
    Public Property AKLuoja As String
    Public Property AKPaivitetty As Nullable(Of Date)
    Public Property AKPaivittaja As String
    Public Property AKKontaktoijaId As Nullable(Of System.Guid)

    Public Overridable Property aspnet_Users As aspnet_Users
    Public Overridable Property hlp_AktiviteetinLaji As hlp_AktiviteetinLaji
    Public Overridable Property hlp_AktiviteetinStatus As hlp_AktiviteetinStatus
    Public Overridable Property hlp_AktiviteettiYhteystapa As hlp_AktiviteettiYhteystapa
    Public Overridable Property Sopimus As Sopimus
    Public Overridable Property Taho As Taho

End Class
