'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aspnet_RolesInGroups
    Public Property GroupId As System.Guid
    Public Property RoleId As System.Guid

    Public Overridable Property aspnet_RoleGroups As aspnet_RoleGroups
    Public Overridable Property aspnet_Roles As aspnet_Roles
    Public Overridable Property aspnet_Roles1 As aspnet_Roles

End Class
