'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_InvCost
    Public Property ICOId As Integer
    Public Property ICONimi As String
    Public Property ICOLuotu As Date
    Public Property ICOLuoja As String
    Public Property ICOPaivitetty As Nullable(Of Date)
    Public Property ICOPaivittaja As String

    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)
    Public Overridable Property KorvauslaskelmaRivi As ICollection(Of KorvauslaskelmaRivi) = New HashSet(Of KorvauslaskelmaRivi)

End Class
