'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Infopallura
    Public Property IFPId As Integer
    Public Property IFPLomake As String
    Public Property IFPKentta As String
    Public Property IFPTeksti As String
    Public Property IFPLuoja As String
    Public Property IFPLuotu As Date
    Public Property IFPPaivittaja As String
    Public Property IFPPaivitetty As Nullable(Of Date)

End Class
