'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_LiiketoiminnanTarve
    Public Property LTOId As Integer
    Public Property LTOLiiketoiminnanTarve As String
    Public Property LTOLuotu As Date
    Public Property LTOLuoja As String
    Public Property LTOPaivitetty As Nullable(Of Date)
    Public Property LTOPaivittaja As String

    Public Overridable Property Kiinteisto As ICollection(Of Kiinteisto) = New HashSet(Of Kiinteisto)

End Class
