'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Kohdekategoria
    Public Property KDKId As Integer
    Public Property KDKKohdeKategoria As String
    Public Property KDKLuotu As Date
    Public Property KDKLuoja As String
    Public Property KDKPaivitetty As Nullable(Of Date)
    Public Property KDKPaivittaja As String

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
