'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_MaaraAlaTarkenne
    Public Property MATId As Integer
    Public Property MATMaaraAlaTarkenne As String
    Public Property MATLuotu As Date
    Public Property MATLuoja As String
    Public Property MATPaivitetty As Nullable(Of Date)
    Public Property MATPaivittaja As String

    Public Overridable Property Kiinteisto As ICollection(Of Kiinteisto) = New HashSet(Of Kiinteisto)

End Class
