'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Asiakastyyppi
    Public Property ATYId As Integer
    Public Property ATYAsiakastyyppi As String
    Public Property ATYLuotu As Date
    Public Property ATYLuoja As String
    Public Property ATYPaivitetty As Nullable(Of Date)
    Public Property ATYPaivittaja As String

    Public Overridable Property Sopimus_Taho As ICollection(Of Sopimus_Taho) = New HashSet(Of Sopimus_Taho)

End Class
