'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_SiirtoOikeus
    Public Property SOIId As Integer
    Public Property SOISiirtoOikeus As String
    Public Property SOILuotu As Date
    Public Property SOILuoja As String
    Public Property SOIPaivitetty As Nullable(Of Date)
    Public Property SOIPaivittaja As String

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)
    Public Overridable Property Sopimus1 As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
