'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Saanto
    Public Property SAAId As Integer
    Public Property SAASaanto As String
    Public Property SAALuotu As Date
    Public Property SAALuoja As String
    Public Property SAAPaivitetty As Nullable(Of Date)
    Public Property SAAPaivittaja As String

    Public Overridable Property Kiinteisto As ICollection(Of Kiinteisto) = New HashSet(Of Kiinteisto)

End Class
