'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Alv
    Public Property ALVId As Integer
    Public Property ALVProsentti As Nullable(Of Decimal)
    Public Property ALVOletus As Nullable(Of Boolean)
    Public Property ALVLuoja As String
    Public Property ALVLuotu As Date
    Public Property ALVPaivittaja As String
    Public Property ALVPaivitetty As Nullable(Of Date)

    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)

End Class
