'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Julkisuusaste
    Public Property JASId As Integer
    Public Property JASJulkisuusaste As String
    Public Property JASLuotu As Date
    Public Property JASLuoja As String
    Public Property JASPaivitetty As Nullable(Of Date)
    Public Property JASPaivittaja As String

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
