'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Kunta
    Public Property KKuntaid As Integer
    Public Property KKunta As String
    Public Property KKuntaSwe As String
    Public Property KKuntaNro As String
    Public Property KPaivittaja As String
    Public Property KPaivitetty As Nullable(Of Date)
    Public Property KLuotu As Nullable(Of Date)
    Public Property KLuoja As String

    Public Overridable Property Kiinteisto As ICollection(Of Kiinteisto) = New HashSet(Of Kiinteisto)
    Public Overridable Property Taho As ICollection(Of Taho) = New HashSet(Of Taho)

End Class
