'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_Sopimusluokka
    Public Property SLUId As Integer
    Public Property SLUSopimusLuokka As String
    Public Property SLULuotu As Date
    Public Property SLULuoja As String
    Public Property SLUPaivitetty As Nullable(Of Date)
    Public Property SLUPaivittaja As String

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
