'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_Sopimustyyppi
    Public Property STYId As Integer
    Public Property STYSopimustyyppi As String
    Public Property STYLuoja As String
    Public Property STYLuotu As Date
    Public Property STYPaivittaja As String
    Public Property STYPaivitetty As Nullable(Of Date)
    Public Property C_kategoria As String
    Public Property STYAsiakirjatarkenne As String

    Public Overridable Property KorvausHinnasto As ICollection(Of KorvausHinnasto) = New HashSet(Of KorvausHinnasto)
    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
