'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_Korvaustyyppi
    Public Property KTYId As Integer
    Public Property KTYKorvaustyyppi As String
    Public Property KTYLuotu As Date
    Public Property KTYLuoja As String
    Public Property KTYPaivitetty As Nullable(Of Date)
    Public Property KTYPaivittaja As String

    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)

End Class
