'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_KorvauslaskemaStatus
    Public Property KSTId As Integer
    Public Property KSTKorvauslaskelmaStatus As String
    Public Property KSTLuotu As Date
    Public Property KSTLuoja As String
    Public Property KSTPaivittaja As String
    Public Property KSTPaivitetty As Nullable(Of Date)

    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)

End Class
