'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Korvauslaskelma
    Public Property KORId As Integer
    Public Property KORSopimusId As Nullable(Of Integer)
    Public Property KORTahoId As Nullable(Of Integer)
    Public Property KORMaksualueId As Nullable(Of Integer)
    Public Property KORKorvaustyyppiId As Nullable(Of Integer)
    Public Property KORKorvauslaskelmaStatusId As Nullable(Of Integer)
    Public Property KORLaskennallinenKorvaus As Nullable(Of Decimal)
    Public Property KORMaksettavaKorvaus As Nullable(Of Decimal)
    Public Property KORMaksettavaKorvausAlkuperainen As Nullable(Of Decimal)
    Public Property KORVanhaSopimusPaattyyiPvm As Nullable(Of Date)
    Public Property KORKorvausProsentti As Nullable(Of Decimal)
    Public Property KORMaksuKuukausiId As Nullable(Of Integer)
    Public Property KORViimeisinMaksuPvm As Nullable(Of Date)
    Public Property KORViimeinenMaksuPvm As Nullable(Of Date)
    Public Property KOREnsimmainenSallittuMaksuPvm As Nullable(Of Date)
    Public Property KORSopimushetkenIndeksiArvo As Nullable(Of Integer)
    Public Property KORNykyinenIndeksiArvo As Nullable(Of Integer)
    Public Property KORIndeksityyppiId As Nullable(Of Integer)
    Public Property KORIndeksiKuukausiId As Nullable(Of Integer)
    Public Property KORIndeksiVuosi As Nullable(Of Integer)
    Public Property KORViite As String
    Public Property KORViesti As String
    Public Property KORProjektinumero As String
    Public Property KORKorvauksenProjektinumero As String
    Public Property KORMaksunSuoritusId As Nullable(Of Integer)
    Public Property KORPuustonOmistajuusId As Nullable(Of Integer)
    Public Property KORPuustonPoistoId As Nullable(Of Integer)
    Public Property KORInfo As String
    Public Property KORLuotu As Date
    Public Property KORLuoja As String
    Public Property KORPaivitetty As Nullable(Of Date)
    Public Property KORPaivittaja As String
    Public Property KORKirjanpidonTiliId As Nullable(Of Integer)
    Public Property KORKirjanpidonKustannuspaikkaId As Nullable(Of Integer)
    Public Property KORInvCostId As Nullable(Of Integer)
    Public Property KORRegulationId As Nullable(Of Integer)
    Public Property KORPurposeId As Nullable(Of Integer)
    Public Property KORLocal1Id As Nullable(Of Integer)
    Public Property KORProjectno As String
    Public Property KORName As String
    Public Property KORTypeOfProject As String
    Public Property KORType As String
    Public Property KOROwner As String
    Public Property KORConcession As String
    Public Property KORCertDate As String
    Public Property KORFieldWorkStarted As Nullable(Of Date)
    Public Property KORProjectClosedA As Nullable(Of Date)
    Public Property KORMaksetaanAlv As Boolean
    Public Property KOROnIndeksi As Boolean
    Public Property KORMaksuehdotId As Nullable(Of Integer)
    Public Property KORViimeisinMaksu As Nullable(Of Decimal)
    Public Property KORViimeisinIndeksi As Nullable(Of Integer)
    Public Property KORViimeisinMaksuIndeksi As Nullable(Of Integer)
    Public Property KOREnsimmainenMaksupaivaAsetettuKasin As Nullable(Of Boolean)
    Public Property KORViimeisinIndeksiVuosi As Nullable(Of Integer)
    Public Property KORAlvId As Nullable(Of Integer)
    Public Property C_korSqlId As Nullable(Of Integer)
    Public Property KORCategory As String

    Public Overridable Property hlp_Alv As hlp_Alv
    Public Overridable Property hlp_Indeksityyppi As hlp_Indeksityyppi
    Public Overridable Property hlp_InvCost As hlp_InvCost
    Public Overridable Property hlp_KirjanpidonKustannuspaikka As hlp_KirjanpidonKustannuspaikka
    Public Overridable Property hlp_Kirjanpidontili As hlp_Kirjanpidontili
    Public Overridable Property hlp_Local1 As hlp_Local1
    Public Overridable Property hlp_Maksualue As hlp_Maksualue
    Public Overridable Property hlp_Maksuehdot As hlp_Maksuehdot
    Public Overridable Property hlp_MaksunSuoritus As hlp_MaksunSuoritus
    Public Overridable Property hlp_Purpose As hlp_Purpose
    Public Overridable Property hlp_PuustonOmistajuus As hlp_PuustonOmistajuus
    Public Overridable Property hlp_PuustonPoisto As hlp_PuustonPoisto
    Public Overridable Property hlp_Regulation As hlp_Regulation
    Public Overridable Property hlps_KorvauslaskemaStatus As hlps_KorvauslaskemaStatus
    Public Overridable Property hlps_Korvaustyyppi As hlps_Korvaustyyppi
    Public Overridable Property hlps_Kuukausi As hlps_Kuukausi
    Public Overridable Property hlps_Kuukausi1 As hlps_Kuukausi
    Public Overridable Property Korvauslaskelma1 As Korvauslaskelma
    Public Overridable Property Korvauslaskelma2 As Korvauslaskelma
    Public Overridable Property Sopimus As Sopimus
    Public Overridable Property Taho As Taho
    Public Overridable Property KorvauslaskelmaRivi As ICollection(Of KorvauslaskelmaRivi) = New HashSet(Of KorvauslaskelmaRivi)
    Public Overridable Property Maksu As ICollection(Of Maksu) = New HashSet(Of Maksu)

End Class
