'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Maksuaineisto
    Public Property MAIId As Integer
    Public Property MAILuotu As Nullable(Of Date)
    Public Property MAILuoja As String
    Public Property MAIPaivitetty As Nullable(Of Date)
    Public Property MAIPaivittaja As String

    Public Overridable Property KirjanpidonAineisto As KirjanpidonAineisto
    Public Overridable Property KirjanpidonAineistoRivi As KirjanpidonAineistoRivi
    Public Overridable Property Maksu As ICollection(Of Maksu) = New HashSet(Of Maksu)

End Class
