'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Maksu_Tiliointi
    Public Property MTLId As Integer
    Public Property MTLMaksuId As Integer
    Public Property MTLSumma As Nullable(Of Decimal)
    Public Property MTLProjektinro As String
    Public Property MTLKirjanpidontili As String
    Public Property MTLKustannuspaikka As String
    Public Property MTLInvCost As String
    Public Property MTLRegulation As String
    Public Property MTLPurpose As String
    Public Property MTLLocal1 As String
    Public Property MTLLuotu As Date
    Public Property MTLLuoja As String
    Public Property MTLAlvOsuus As Nullable(Of Decimal)
    Public Property MTLSummaIlmanAlv As Nullable(Of Decimal)
    Public Property MTLCategory As String

    Public Overridable Property Maksu As Maksu

End Class
