'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sopimus
    Public Property SOPId As Integer
    Public Property SOPSopimustyyppiId As Nullable(Of Integer)
    Public Property SOPPaasopimusId As Nullable(Of Integer)
    Public Property SOPAlkaa As Nullable(Of Date)
    Public Property SOPPaattyy As Nullable(Of Date)
    Public Property SOPKestoId As Nullable(Of Integer)
    Public Property SOPProjektiAloitusPvm As Nullable(Of Date)
    Public Property SOPMuuTunniste As String
    Public Property SOPIban As String
    Public Property SOPJuridinenYhtioId As Nullable(Of Integer)
    Public Property SOPSopimuksenLaatija As String
    Public Property SOPVastuuyksikkoId As Nullable(Of Integer)
    Public Property SOPProjektinumero As String
    Public Property SOPPylvasmaara As Nullable(Of Integer)
    Public Property SOPLuonnonsuojelualue As Boolean
    Public Property SOPPylvasvali As String
    Public Property SOPMaantieteellinenVali As String
    Public Property SOPMuuntamoalue As Nullable(Of Decimal)
    Public Property SOPJulkisuusasteId As Nullable(Of Integer)
    Public Property SOPKorvaa As String
    Public Property SOPSopimuksenTilaId As Nullable(Of Integer)
    Public Property SOPSopimusvuosi As String
    Public Property SOPInfo As String
    Public Property SOPLuotu As Date
    Public Property SOPLuoja As String
    Public Property SOPPaivittaja As String
    Public Property SOPPaivitetty As Nullable(Of Date)
    Public Property C_JasId As Nullable(Of Integer)
    Public Property C_SQLId As Nullable(Of Integer)
    Public Property C_kiineistotunnus As String
    Public Property C_kiinteistotunnus As String
    Public Property SOPAlkuperainenKorvaus As Nullable(Of Decimal)
    Public Property SOPDFRooliId As Nullable(Of Integer)
    Public Property SOPSopimusluokkaId As Nullable(Of Integer)
    Public Property SOPSopimuksenAlaluokkaId As Nullable(Of Integer)
    Public Property SOPSopimuksenEhtoversioId As Nullable(Of Integer)
    Public Property SOPKarttaliite As String
    Public Property SOPKuvaus As String
    Public Property SOPVerkonhaltijanAllekirjoitusPvm As Nullable(Of Date)
    Public Property SOPAsiakkaanAllekirjoitusPvm As Nullable(Of Date)
    Public Property SOPSopimuksenIrtisanomisaika As Nullable(Of Integer)
    Public Property SOPSopimuksenIrtisanomistoimet As String
    Public Property SOPVerkohaltijaSiirtoOikeusId As Nullable(Of Integer)
    Public Property SOPVastaosapuoliSiirtoOikeusId As Nullable(Of Integer)
    Public Property SOPAlkuperainenYhtioId As Nullable(Of Integer)
    Public Property SOPIrtisanomispvm As Nullable(Of Date)
    Public Property SOPPCSNumero As String
    Public Property SOPProjektinvalvoja As String
    Public Property SOPPuustonPoistoId As Nullable(Of Integer)
    Public Property SOPPuustonOmistajuusId As Nullable(Of Integer)
    Public Property SOPJatkoaika As Nullable(Of Integer)
    Public Property SOPLaskennallinenPaattymispvm As Nullable(Of Date)
    Public Property SOPKohdekategoriaId As Nullable(Of Integer)
    Public Property SOPTiedostoHaettu As Boolean
    Public Property SOPMetatiedotPaivitetty As Boolean
    Public Property SOPLuonnos As Boolean
    Public Property SOPKieliId As Nullable(Of Integer)
    Public Property SOPErityisehdot As String
    Public Property SOPYlasopimuksenTyyppiId As Nullable(Of Integer)
    Public Property SOPLupatahoId As Nullable(Of Integer)
    Public Property SOPKorvaukseton As Boolean
    Public Property SOPMappitunniste As String
    Public Property SOPCaceTehtava As String
    Public Property SOPVerkonhaltijaAllekirjoittaja As String
    Public Property SOPSopimusarkistosiirtoTehty As Nullable(Of Date)
    Public Property SOPGuid As String

    Public Overridable Property Aktiviteetti As ICollection(Of Aktiviteetti) = New HashSet(Of Aktiviteetti)
    Public Overridable Property hlp_DFRooli As hlp_DFRooli
    Public Overridable Property hlp_Julkisuusaste As hlp_Julkisuusaste
    Public Overridable Property hlp_Kieli As hlp_Kieli
    Public Overridable Property hlp_Kohdekategoria As hlp_Kohdekategoria
    Public Overridable Property hlp_Lupataho As hlp_Lupataho
    Public Overridable Property hlp_PuustonOmistajuus As hlp_PuustonOmistajuus
    Public Overridable Property hlp_PuustonPoisto As hlp_PuustonPoisto
    Public Overridable Property hlp_SiirtoOikeus As hlp_SiirtoOikeus
    Public Overridable Property hlp_SiirtoOikeus1 As hlp_SiirtoOikeus
    Public Overridable Property hlp_SopimuksenAlaluokka As hlp_SopimuksenAlaluokka
    Public Overridable Property hlp_SopimuksenEhtoversio As hlp_SopimuksenEhtoversio
    Public Overridable Property hlp_SopimuksenKesto As hlp_SopimuksenKesto
    Public Overridable Property hlps_SopimuksenTila As hlps_SopimuksenTila
    Public Overridable Property hlps_Sopimusluokka As hlps_Sopimusluokka
    Public Overridable Property hlps_Sopimustyyppi As hlps_Sopimustyyppi
    Public Overridable Property hlps_YlasopimuksenTyyppi As hlps_YlasopimuksenTyyppi
    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)
    Public Overridable Property Maksu As ICollection(Of Maksu) = New HashSet(Of Maksu)
    Public Overridable Property Sopimus_Kiinteisto As ICollection(Of Sopimus_Kiinteisto) = New HashSet(Of Sopimus_Kiinteisto)
    Public Overridable Property Sopimus1 As ICollection(Of Sopimus) = New HashSet(Of Sopimus)
    Public Overridable Property Sopimus2 As Sopimus
    Public Overridable Property Sopimus11 As Sopimus
    Public Overridable Property Sopimus3 As Sopimus
    Public Overridable Property Taho As Taho
    Public Overridable Property Sopimus_Taho As ICollection(Of Sopimus_Taho) = New HashSet(Of Sopimus_Taho)
    Public Overridable Property Taho1 As Taho
    Public Overridable Property Taho2 As Taho
    Public Overridable Property Sopimus_Tuloste As ICollection(Of Sopimus_Tuloste) = New HashSet(Of Sopimus_Tuloste)
    Public Overridable Property Tiedosto As ICollection(Of Tiedosto) = New HashSet(Of Tiedosto)
    Public Overridable Property Tunnisteyksikko As ICollection(Of Tunnisteyksikko) = New HashSet(Of Tunnisteyksikko)

End Class
