'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Taho
    Public Property TAHTahoId As Integer
    Public Property TAHTyyppiId As Nullable(Of Integer)
    Public Property TAHSukunimi As String
    Public Property TAHEdellinenSukunimi As String
    Public Property TAHEtunimi As String
    Public Property TAHNimitarkenne As String
    Public Property TAHOrganisaationTyyppiId As Nullable(Of Integer)
    Public Property TAHYtunnus As String
    Public Property TAHLisaosoite As String
    Public Property TAHPostitusosoite As String
    Public Property TAHPostituspostinro As String
    Public Property TAHPostituspostitmp As String
    Public Property TAHMaaId As Nullable(Of Integer)
    Public Property TAHTilinumero As String
    Public Property TAHPuhelin As String
    Public Property TAHEmail As String
    Public Property TAHAlvVelvollinen As Boolean
    Public Property TAHPassivointipvm As Nullable(Of Date)
    Public Property TAHPassivoinninsyyId As Nullable(Of Integer)
    Public Property TAHAktiivi As Boolean
    Public Property TAHInfo As String
    Public Property TAHPaivittaja As String
    Public Property TAHPaivitetty As Nullable(Of Date)
    Public Property TAHLuotu As Date
    Public Property TAHLuoja As String
    Public Property C_tahsqlid As Nullable(Of Integer)
    Public Property TAHKuntaId As Nullable(Of Integer)
    Public Property TAHBic As String
    Public Property TAHBicKoodiId As Nullable(Of Integer)
    Public Property TAHKirjanpidonYritystunniste As String
    Public Property TAHKirjanpidonProjektitunniste As String
    Public Property TAHConcession As String
    Public Property C_tahsqlid2 As Nullable(Of Integer)
    Public Property TAHExcelTuontiId As Nullable(Of Integer)

    Public Overridable Property Aktiviteetti As ICollection(Of Aktiviteetti) = New HashSet(Of Aktiviteetti)
    Public Overridable Property hlp_BicKoodi As hlp_BicKoodi
    Public Overridable Property hlp_Kunta As hlp_Kunta
    Public Overridable Property hlp_Maa As hlp_Maa
    Public Overridable Property hlp_PassivoinninSyy As hlp_PassivoinninSyy
    Public Overridable Property hlps_OrganisaationTyyppi As hlps_OrganisaationTyyppi
    Public Overridable Property hlps_TahoTyyppi As hlps_TahoTyyppi
    Public Overridable Property Kiinteisto As ICollection(Of Kiinteisto) = New HashSet(Of Kiinteisto)
    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)
    Public Overridable Property Maksu As ICollection(Of Maksu) = New HashSet(Of Maksu)
    Public Overridable Property Maksu1 As ICollection(Of Maksu) = New HashSet(Of Maksu)
    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)
    Public Overridable Property Sopimus1 As ICollection(Of Sopimus) = New HashSet(Of Sopimus)
    Public Overridable Property Sopimus2 As ICollection(Of Sopimus) = New HashSet(Of Sopimus)
    Public Overridable Property Sopimus_Taho As ICollection(Of Sopimus_Taho) = New HashSet(Of Sopimus_Taho)

End Class
