'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tunnisteyksikko
    Public Property TUYId As Integer
    Public Property TUYTunnus As String
    Public Property TUYNimi As String
    Public Property TUYLinjaOsa As String
    Public Property TUYPGTunniste As String
    Public Property TUYKoordinaatit As String
    Public Property TUYSopimusId As Nullable(Of Integer)
    Public Property TUYInfo As String
    Public Property TUYLuotu As Nullable(Of Date)
    Public Property TUYLuoja As String
    Public Property TUYPaivitetty As Nullable(Of Date)
    Public Property TUYPaivittaja As String
    Public Property TUYAktiivinen As Boolean
    Public Property TUYPGTunnus As String
    Public Property TUYPGKoordinaatti1 As Nullable(Of Integer)
    Public Property TUYPGKoordinaatti2 As Nullable(Of Integer)
    Public Property TUYTunnisteyksikkoTyyppiId As Nullable(Of Integer)
    Public Property TUYKohdetieto As String
    Public Property C_tuySqlId As Nullable(Of Integer)

    Public Overridable Property hlp_TunnisteyksikkoTyyppi As hlp_TunnisteyksikkoTyyppi
    Public Overridable Property Sopimus As Sopimus

End Class
