'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Poimintajoukko_testi

  '''<summary>
  '''PoimintaTyokalut1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PoimintaTyokalut1 As Global.appSopimusrekisteri.PoimintaTyokalut

  '''<summary>
  '''lblPoimintaehdotNaytolle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPoimintaehdotNaytolle As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''hlExcel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hlExcel As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''btnUusiPoiminta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnUusiPoiminta As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnLisaaPoimintaan control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnLisaaPoimintaan As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnPoistaPoiminnasta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnPoistaPoiminnasta As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnNollaa control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnNollaa As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''gvPoimitut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gvPoimitut As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''lblPageCount control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPageCount As Global.System.Web.UI.WebControls.Label
End Class
