'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Lisaa_poimituille

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''hdnSopimusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdnSopimusId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''hdnKorvauslaskelmaId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hdnKorvauslaskelmaId As Global.System.Web.UI.WebControls.HiddenField

  '''<summary>
  '''ddKorvaustyyppi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddKorvaustyyppi As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddMaksukuukausi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddMaksukuukausi As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ddMaksunSuoritus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddMaksunSuoritus As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnHae control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnHae As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''custValKorvauslaskelmiaOnOlemassa control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents custValKorvauslaskelmiaOnOlemassa As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''lblSopimus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblSopimus As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblKorvauslaskelma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKorvauslaskelma As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ddMAKMaksuStatusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddMAKMaksuStatusId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ReqValMAKMaksupaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValMAKMaksupaiva As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ComValMAKMaksupaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValMAKMaksupaiva As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtMAKMaksupaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMAKMaksupaiva As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''imgMAKMaksupaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgMAKMaksupaiva As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''calMAKMaksupaiva control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calMAKMaksupaiva As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''ReqValMAKSumma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ReqValMAKSumma As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''ComValMAKSumma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValMAKSumma As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''custValSummaTasmaa control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents custValSummaTasmaa As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''txtMAKSumma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMAKSumma As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtMAKInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMAKInfo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnPeruuta As Global.System.Web.UI.WebControls.Button
End Class
