'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Taho.Organisaatio
    
    Partial Public Class Muokkaa
        
        '''<summary>
        '''Tyokalut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut
        
        '''<summary>
        '''Haku control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue
        
        '''<summary>
        '''formData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents formData As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ValidationSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
        
        '''<summary>
        '''Paivitetty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Paivitetty As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Paivittaja control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Paivittaja As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Luotu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Luotu As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Luoja control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Luoja As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ifpOrganisaationTyyppiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpOrganisaationTyyppiId As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''OrganisaationTyyppiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrganisaationTyyppiId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ifpSukunimi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpSukunimi As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''rvSukunimi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvSukunimi As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''Sukunimi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Sukunimi As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpNimitarkenne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpNimitarkenne As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''Nimitarkenne control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Nimitarkenne As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpYtunnus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpYtunnus As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''Ytunnus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Ytunnus As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpPostitusosoite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpPostitusosoite As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''rvPostitusosoite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvPostitusosoite As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''Postitusosoite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Postitusosoite As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpPostituspostinro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpPostituspostinro As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''rvPostituspostinro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvPostituspostinro As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''ComValPostituspostinro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ComValPostituspostinro As Global.System.Web.UI.WebControls.CompareValidator
        
        '''<summary>
        '''Postituspostinro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Postituspostinro As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnHaePostitoimipaikka control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHaePostitoimipaikka As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''ifpPostituspostitmp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpPostituspostitmp As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''rvPostituspostitmp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvPostituspostitmp As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''Postituspostitmp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Postituspostitmp As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpKuntaId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpKuntaId As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''KuntaId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KuntaId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ifpMaaId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpMaaId As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''MaaId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MaaId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ifpPuhelin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpPuhelin As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''rvPuhelin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvPuhelin As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''Puhelin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Puhelin As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpEmail As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''Email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpTilinumero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpTilinumero As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''CusValTilinumero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CusValTilinumero As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''Tilinumero control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tilinumero As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpBicKoodiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpBicKoodiId As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''CusValBic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CusValBic As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''BicKoodiId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BicKoodiId As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ifpBicKoodiMuu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpBicKoodiMuu As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''BicKoodiMuu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BicKoodiMuu As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpAlvVelvollinen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpAlvVelvollinen As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''AlvVelvollinen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AlvVelvollinen As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''ifpKirjanpidonYritystunniste control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpKirjanpidonYritystunniste As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''KirjanpidonYritystunniste control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KirjanpidonYritystunniste As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpKirjanpidonProjektitunniste control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpKirjanpidonProjektitunniste As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''KirjanpidonProjektitunniste control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KirjanpidonProjektitunniste As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpConcession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpConcession As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''Concession control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Concession As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ifpInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifpInfo As Global.appSopimusrekisteri.Infopallura
        
        '''<summary>
        '''Info control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Info As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btTallenna control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btPeruuta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
