'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HaeAlasopimus

    '''<summary>
    '''Tyokalut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

    '''<summary>
    '''Haku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

    '''<summary>
    '''lblSopimusnumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSopimusnumero As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvVapaaHaku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvVapaaHaku As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cSopimusnumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cSopimusnumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHae control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHae As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPeruuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPeruuta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTiedot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTiedot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvHakutulos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHakutulos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnUusiSopimus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUusiSopimus As Global.System.Web.UI.WebControls.Button
End Class
