'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Korvauslaskelmat
    
    '''<summary>
    '''gvKorvauslaskelma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvKorvauslaskelma As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btLisaaKorvauslaskelma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btLisaaKorvauslaskelma As Global.System.Web.UI.WebControls.Button
End Class
