'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aspnet_PersonalizationPerUser
    Public Property Id As System.Guid
    Public Property PathId As Nullable(Of System.Guid)
    Public Property UserId As Nullable(Of System.Guid)
    Public Property PageSettings As Byte()
    Public Property LastUpdatedDate As Date

    Public Overridable Property aspnet_Paths As aspnet_Paths
    Public Overridable Property aspnet_Users As aspnet_Users

End Class
