'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aspnet_RoleGroups
    Public Property ApplicationId As System.Guid
    Public Property GroupId As System.Guid
    Public Property GroupName As String
    Public Property LoweredGroupName As String
    Public Property Description As String

    Public Overridable Property aspnet_Applications As aspnet_Applications
    Public Overridable Property aspnet_RolesInGroups As ICollection(Of aspnet_RolesInGroups) = New HashSet(Of aspnet_RolesInGroups)
    Public Overridable Property aspnet_UsersInGroups As ICollection(Of aspnet_UsersInGroups) = New HashSet(Of aspnet_UsersInGroups)

End Class
