'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aspnet_AccessRules
    Public Property ApplicationId As System.Guid
    Public Property AccessRuleId As System.Guid
    Public Property AccessRuleName As String
    Public Property LoweredAccessRuleName As String
    Public Property Description As String

    Public Overridable Property aspnet_Applications As aspnet_Applications
    Public Overridable Property aspnet_Roles As ICollection(Of aspnet_Roles) = New HashSet(Of aspnet_Roles)

End Class
