'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_TunnisteyksikkoTyyppi
    Public Property TTYId As Integer
    Public Property TTYTunnisteYksikkoTyyppi As String
    Public Property TTYLuotu As Date
    Public Property TTYLuoja As String
    Public Property TTYPaivitetty As Nullable(Of Date)
    Public Property TTYPaivittaja As String

    Public Overridable Property Tunnisteyksikko As ICollection(Of Tunnisteyksikko) = New HashSet(Of Tunnisteyksikko)

End Class
