'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_BicKoodi
    Public Property BKId As Integer
    Public Property BKKoodi As String
    Public Property BKPankki As String
    Public Property BKRahalaitosTunnus As String
    Public Property BKLuotu As Nullable(Of Date)
    Public Property BKLuoja As String
    Public Property BKPaivitetty As Nullable(Of Date)
    Public Property BKPaivittaja As String

    Public Overridable Property Taho As ICollection(Of Taho) = New HashSet(Of Taho)

End Class
