'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_PuustonPoisto
    Public Property PPOId As Integer
    Public Property PPOPuustonPoisto As String
    Public Property PPOLuotu As Date
    Public Property PPOLuoja As String
    Public Property PPOPaivitetty As Nullable(Of Date)
    Public Property PPOPaivittaja As String
    Public Property PPOPuustonPoistoSwe As String

    Public Overridable Property Korvauslaskelma As ICollection(Of Korvauslaskelma) = New HashSet(Of Korvauslaskelma)
    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
