'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_SopimusFormaatti
    Public Property SFOId As Integer
    Public Property SFOSopimusFormaatti As String
    Public Property SFOLuotu As Date
    Public Property SFOLuoja As String
    Public Property SFOPaivitetty As Nullable(Of Date)
    Public Property SFOPaivittaja As String

    Public Overridable Property Tiedosto As ICollection(Of Tiedosto) = New HashSet(Of Tiedosto)

End Class
