'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_SopimuksenEhtoversio
    Public Property SEHId As Integer
    Public Property SEHSopimuksenEhtoversio As String
    Public Property SEHLuotu As Date
    Public Property SEHLuoja As String
    Public Property SEHPaivitetty As Nullable(Of Date)
    Public Property SEHPaivittaja As String

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
