'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Metsatyyppi
    Public Property MTYId As Integer
    Public Property MTYMetsatyyppi As String
    Public Property MTYLuotu As Date
    Public Property MTYLuoja As String
    Public Property MTYPaivitetty As Nullable(Of Date)
    Public Property MTYPaivittaja As String

    Public Overridable Property KorvausHinnasto As ICollection(Of KorvausHinnasto) = New HashSet(Of KorvausHinnasto)

End Class
