'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Puustolaji
    Public Property PLAId As Integer
    Public Property PLAPuustolaji As String
    Public Property PLALuotu As Date
    Public Property PLALuoja As String
    Public Property PLAPaivitetty As Nullable(Of Date)
    Public Property PLAPaivittaja As String

    Public Overridable Property KorvausHinnasto As ICollection(Of KorvausHinnasto) = New HashSet(Of KorvausHinnasto)

End Class
