'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_Yksikko
    Public Property YKSId As Integer
    Public Property YKSKorvausyksikko As String
    Public Property YKSKerroin As Nullable(Of Decimal)
    Public Property YKSLuotu As Date
    Public Property YKSLuoja As String
    Public Property YKSPaivittaja As String
    Public Property YKSPaivitetty As Nullable(Of Date)
    Public Property C_Korvausyksikko As String
    Public Property YKSKorvausyksikonTyyppiId As Nullable(Of Integer)

    Public Overridable Property hlps_KorvausyksikonTyyppi As hlps_KorvausyksikonTyyppi
    Public Overridable Property KorvausHinnasto As ICollection(Of KorvausHinnasto) = New HashSet(Of KorvausHinnasto)
    Public Overridable Property KorvauslaskelmaRivi As ICollection(Of KorvauslaskelmaRivi) = New HashSet(Of KorvauslaskelmaRivi)

End Class
