'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlp_AktiviteetinStatus
    Public Property ASId As Integer
    Public Property ASAktiviteetinStatus As String
    Public Property ASLuotu As Date
    Public Property ASLuoja As String
    Public Property ASPaivitetty As Nullable(Of Date)
    Public Property ASPaivittaja As String

    Public Overridable Property Aktiviteetti As ICollection(Of Aktiviteetti) = New HashSet(Of Aktiviteetti)

End Class
