'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_OrganisaationTyyppi
    Public Property ORTId As Integer
    Public Property ORTTyyppi As String
    Public Property ORTLuotu As Date
    Public Property ORTLuoja As String
    Public Property ORTPaivitetty As Nullable(Of Date)
    Public Property ORTPaivittaja As String

    Public Overridable Property Taho As ICollection(Of Taho) = New HashSet(Of Taho)

End Class
