'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_YlasopimuksenTyyppi
    Public Property YSTId As Integer
    Public Property YSTYlasopimuksenTyyppi As String
    Public Property YSTLuoja As String
    Public Property YSTLuotu As Date
    Public Property YSTPaivittaja As String
    Public Property YSTPaivitetty As Nullable(Of Date)

    Public Overridable Property Sopimus As ICollection(Of Sopimus) = New HashSet(Of Sopimus)

End Class
