'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hlps_MaksuStatus
    Public Property MSAId As Integer
    Public Property MSAMaksuStatus As String
    Public Property MSALuotu As Date
    Public Property MSALuoja As String
    Public Property MSAPaivitetty As Nullable(Of Date)
    Public Property MSAPaivittaja As String

    Public Overridable Property Maksu As ICollection(Of Maksu) = New HashSet(Of Maksu)

End Class
