'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Kiinteisto
    Public Property KIIId As Integer
    Public Property KIIKiinteisto As String
    Public Property KIITahoId As Nullable(Of Integer)
    Public Property KIIKatuosoite As String
    Public Property KIIPostitoimipaikka As String
    Public Property KIIPostinumero As String
    Public Property KIIMaaId As Nullable(Of Integer)
    Public Property KIIRekisterinumero As String
    Public Property KIIKyla As String
    Public Property KIIKylanumero As Nullable(Of Integer)
    Public Property KIIKylaId As Nullable(Of Integer)
    Public Property KIIKunta As String
    Public Property KIIKuntanumero As Nullable(Of Integer)
    Public Property KIIKuntaId As Nullable(Of Integer)
    Public Property KIIKiinteistotunnus As String
    Public Property KIIKiinteistotunnusLyhyt As String
    Public Property KIIPintaAla As Nullable(Of Decimal)
    Public Property KIIMaapintaAla As Nullable(Of Decimal)
    Public Property KIIVesipintaAla As Nullable(Of Decimal)
    Public Property KIIKortteli As String
    Public Property KIITontti As String
    Public Property KIIMaaraAla As String
    Public Property KIIMaaraAlaTarkenneId As Nullable(Of Integer)
    Public Property KIIKiinteistoverotettuVuosi As Nullable(Of Integer)
    Public Property KIIAssetTunniste As Nullable(Of Integer)
    Public Property KIIRasitteet As String
    Public Property KIIKiinnitykset As String
    Public Property KIIOmistusosuus As Nullable(Of Integer)
    Public Property KIIOmistusosuusTotal As Nullable(Of Integer)
    Public Property KIILiiketoiminnanTarveId As Nullable(Of Integer)
    Public Property KIISaantoId As Nullable(Of Integer)
    Public Property KIIInfo As String
    Public Property KIILuoja As String
    Public Property KIILuotu As Date
    Public Property KIIPaivittaja As String
    Public Property KIIPaivitetty As Nullable(Of Date)
    Public Property C_kiisqlId As Nullable(Of Integer)
    Public Property KIIAlueTarkenne As String
    Public Property KIIExcelTuontiId As Nullable(Of Integer)

    Public Overridable Property hlp_Kunta As hlp_Kunta
    Public Overridable Property hlp_Kyla As hlp_Kyla
    Public Overridable Property hlp_LiiketoiminnanTarve As hlp_LiiketoiminnanTarve
    Public Overridable Property hlp_Maa As hlp_Maa
    Public Overridable Property hlp_MaaraAlaTarkenne As hlp_MaaraAlaTarkenne
    Public Overridable Property hlp_Saanto As hlp_Saanto
    Public Overridable Property Taho As Taho
    Public Overridable Property Sopimus_Kiinteisto As ICollection(Of Sopimus_Kiinteisto) = New HashSet(Of Sopimus_Kiinteisto)

End Class
