'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KirjanpidonAineisto
    Public Property record_type As String
    Public Property batch_id As Integer
    Public Property application_id As String
    Public Property org_id As String
    Public Property check_sum As Decimal

    Public Overridable Property Maksuaineisto As Maksuaineisto

End Class
