'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KorvausHinnasto
    Public Property KHIId As Integer
    Public Property KHIAlkuPvm As Nullable(Of Date)
    Public Property KHILoppuPvm As Nullable(Of Date)
    Public Property KHISopimustyyppiId As Nullable(Of Integer)
    Public Property KHIHinnastoKategoriaId As Nullable(Of Integer)
    Public Property KHIHinnastoAlakategoriaId As Nullable(Of Integer)
    Public Property KHIKorvauslaji As String
    Public Property KHIKuvaus As String
    Public Property KHIArvonPeruste As String
    Public Property KHIMaksuAlueId As Nullable(Of Integer)
    Public Property KHIMetsatyyppiId As Nullable(Of Integer)
    Public Property KHIPuustolajiId As Nullable(Of Integer)
    Public Property KHIPuustonIka As Nullable(Of Integer)
    Public Property KHITaimistonValtapituus As Nullable(Of Decimal)
    Public Property KHITiheyskerroin As Nullable(Of Decimal)
    Public Property KHIYksikkkohinta As Nullable(Of Decimal)
    Public Property KHIYksikkoId As Nullable(Of Integer)
    Public Property KHIYksikkohinnanTarkenne As String
    Public Property KHIAktiivinen As Boolean
    Public Property KHIInfo As String
    Public Property KHILuotu As Date
    Public Property KHILuoja As String
    Public Property KHIPaivittaja As String
    Public Property KHIPaivitetty As Nullable(Of Date)

    Public Overridable Property hlp_HinnastoAlakategoria As hlp_HinnastoAlakategoria
    Public Overridable Property hlp_HinnastoKategoria As hlp_HinnastoKategoria
    Public Overridable Property hlp_Maksualue As hlp_Maksualue
    Public Overridable Property hlp_Metsatyyppi As hlp_Metsatyyppi
    Public Overridable Property hlp_Puustolaji As hlp_Puustolaji
    Public Overridable Property hlp_Yksikko As hlp_Yksikko
    Public Overridable Property hlps_Sopimustyyppi As hlps_Sopimustyyppi
    Public Overridable Property KorvauslaskelmaRivi As ICollection(Of KorvauslaskelmaRivi) = New HashSet(Of KorvauslaskelmaRivi)

End Class
