'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Maksu
    Public Property MAKId As Integer
    Public Property MAKMaksuaineistoId As Nullable(Of Integer)
    Public Property MAKKorvauslaskelmaId As Nullable(Of Integer)
    Public Property MAKMaksupaiva As Nullable(Of Date)
    Public Property MAKSumma As Nullable(Of Decimal)
    Public Property MAKVero As Nullable(Of Decimal)
    Public Property MAKTilinumero As String
    Public Property MAKBic As String
    Public Property MAKViite As String
    Public Property MAKViesti As String
    Public Property MAKIndeksiKuukausiId As Nullable(Of Integer)
    Public Property MAKIndeksi As Nullable(Of Integer)
    Public Property MAKKirjanpidonTiliId As Nullable(Of Integer)
    Public Property MAKKustannuspaikka As String
    Public Property MAKMaksuStatusId As Nullable(Of Integer)
    Public Property MAKLaskunNumero As String
    Public Property MAKEraTunniste As String
    Public Property MAKAjoPvm As Nullable(Of Date)
    Public Property MAKVuosi As Nullable(Of Integer)
    Public Property MAKInfo As String
    Public Property MAKLuotu As Nullable(Of Date)
    Public Property MAKLuoja As String
    Public Property MAKPaivitetty As Nullable(Of Date)
    Public Property MAKPaivittaja As String
    Public Property MAKSaajaId As Nullable(Of Integer)
    Public Property MAKSaaja As String
    Public Property MAKOnIndeksi As Boolean
    Public Property MAKIndeksityyppiId As Nullable(Of Integer)
    Public Property MAKMaksuIndeksi As Nullable(Of Integer)
    Public Property MAKAlvOsuus As Nullable(Of Decimal)
    Public Property MAKJuridinenYhtioId As Nullable(Of Integer)
    Public Property MAKMaksajanNimi As String
    Public Property MAKMaksajanTilinro As String
    Public Property MAKMaksajanBicKoodi As String
    Public Property MAKSopimusId As Nullable(Of Integer)
    Public Property MAKKirjanpidonTunniste As String
    Public Property MAKPalvelutunnus As String
    Public Property MAKPassivoitu As Boolean
    Public Property MAKSummaIlmanAlv As Nullable(Of Decimal)
    Public Property MAKIndeksiVuosi As Nullable(Of Integer)
    Public Property C_makSqlId As Nullable(Of Integer)
    Public Property MAKAlv As Nullable(Of Decimal)
    Public Property MAKIfsMaksupvm As Nullable(Of Date)
    Public Property MAKIfsLaskunro As String

    Public Overridable Property hlp_Indeksityyppi As hlp_Indeksityyppi
    Public Overridable Property hlp_Kirjanpidontili As hlp_Kirjanpidontili
    Public Overridable Property hlps_Kuukausi As hlps_Kuukausi
    Public Overridable Property hlps_MaksuStatus As hlps_MaksuStatus
    Public Overridable Property Korvauslaskelma As Korvauslaskelma
    Public Overridable Property Maksuaineisto As Maksuaineisto
    Public Overridable Property Sopimus As Sopimus
    Public Overridable Property Taho As Taho
    Public Overridable Property Taho1 As Taho
    Public Overridable Property Maksu_Tiliointi As ICollection(Of Maksu_Tiliointi) = New HashSet(Of Maksu_Tiliointi)

End Class
