'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SopimusarkistoLoki
    Public Property SALId As Integer
    Public Property SALTunnistetyyppi As String
    Public Property SALTunniste As String
    Public Property SALOperaatio As String
    Public Property SALTulos As String
    Public Property SALLuoja As String
    Public Property SALLuotu As Nullable(Of Date)

End Class
