'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sopimus_Kiinteisto
    Public Property SKId As Integer
    Public Property SKSopimusId As Integer
    Public Property SKKiinteistoId As Integer
    Public Property SKLuoja As String
    Public Property SKLuotu As Date
    Public Property SKPaivittaja As String
    Public Property SKPaivitetty As Nullable(Of Date)
    Public Property SKExcelTuontiId As Nullable(Of Integer)

    Public Overridable Property Kiinteisto As Kiinteisto
    Public Overridable Property Sopimus As Sopimus

End Class
