'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sopimus_Tuloste
    Public Property STLId As Integer
    Public Property STLSopimusId As Integer
    Public Property STLTuloste As Byte()
    Public Property STLLuoja As String
    Public Property STLLuotu As Date
    Public Property STLPaivittaja As String
    Public Property STLPaivitetty As Nullable(Of Date)

    Public Overridable Property Sopimus As Sopimus

End Class
