'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tiedosto
    Public Property TIEId As Integer
    Public Property TIETiedostoNimi As String
    Public Property TIEURL As String
    Public Property TIESelite As String
    Public Property TIETiedostoLahdeId As Nullable(Of Integer)
    Public Property TIESopimusId As Nullable(Of Integer)
    Public Property TIESharePointId As Nullable(Of Integer)
    Public Property TIEArkistonSijaintiId As Nullable(Of Integer)
    Public Property TIEDocumentID As String
    Public Property TIEArkistointiTunniste As String
    Public Property TIESivuja As Nullable(Of Integer)
    Public Property TIEInfo As String
    Public Property TIELuotu As Date
    Public Property TIELuoja As String
    Public Property TIEPaivitetty As Nullable(Of Date)
    Public Property TIEPaivittaja As String
    Public Property TIEAsiakirjaTarkenneId As Nullable(Of Integer)
    Public Property TIESopimusFormaattiId As Nullable(Of Integer)
    Public Property TIEAsiakirjatarkenne As String
    Public Property TIEMFilesVault As Nullable(Of System.Guid)
    Public Property TIEMFilesType As Integer
    Public Property TIEMFilesId As Nullable(Of Integer)
    Public Property TIEMFilesObject As Nullable(Of System.Guid)

    Public Overridable Property hlp_ArkistonSijainti As hlp_ArkistonSijainti
    Public Overridable Property hlp_AsiakirjaTarkenne As hlp_AsiakirjaTarkenne
    Public Overridable Property hlp_SopimusFormaatti As hlp_SopimusFormaatti
    Public Overridable Property hlps_Tiedostolahde As hlps_Tiedostolahde
    Public Overridable Property Sopimus As Sopimus

End Class
