'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tahohaku

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''txtTAHEtunimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHEtunimi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtTAHSukunimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHSukunimi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtTAHTahoId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHTahoId As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtTAHPostitusosoite control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHPostitusosoite As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmpTAHPostituspostinro control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmpTAHPostituspostinro As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtTAHPostituspostinro control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHPostituspostinro As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtTAHPostituspostitmp control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTAHPostituspostitmp As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSOPId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSOPId As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSOPMuuTunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSOPMuuTunnus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnHaku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnHaku As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnPeruuta As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''gwTulokset control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gwTulokset As Global.System.Web.UI.WebControls.GridView

  '''<summary>
  '''btnLisaaHenkilo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnLisaaHenkilo As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnLisaaOrganisaatio control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnLisaaOrganisaatio As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lblLukumaara control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblLukumaara As Global.System.Web.UI.WebControls.Label
End Class
