CREATE TABLE TiedostoImport (
	TIIId INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	TIITiedostoId INT NULL,
	TIISopimusId INT NULL,
	TIITiedostoNimi VARCHAR(600) NULL,
	TIIMFilesVault VARCHAR(600) NULL,
	TIIMFilesType INT NULL,
	TIIMFilesId INT NULL,
	TIIMFilesObject VARCHAR(600) NULL,
	TIILuotu DATETIME NOT NULL,
	TIILuoja VARCHAR(300) NOT NULL,
	TIISessio VARCHAR(300) NOT NULL,
	TIIKasitelty BIT NOT NULL DEFAULT(0)
)
GO

CREATE INDEX IX_TiedostoImport_TIITiedostoId
ON TiedostoImport (TIITiedostoId); 