name: 'Notify Slack'
description: 'Notify Slack'

inputs:
  message:
    description: "Message to send"
    required: true
  webhook:
    description: "Slack webhook"
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify slack
      shell: bash
      run: |
        curl -d "{\"text\": \"${{ inputs.message }}\"}" -X POST https://hooks.slack.com/services/${{ inputs.webhook }}