'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TunnisteyksikonMuokkaus

  '''<summary>
  '''Tyokalut control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Tyokalut As Global.appSopimusrekisteri.Tyokalut

  '''<summary>
  '''Haku control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Haku As Global.appSopimusrekisteri.Hakualue

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''phPaivitystiedot control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phPaivitystiedot As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''lblTUYPaivitetty control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTUYPaivitetty As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTUYPaivittaja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTUYPaivittaja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTUYLuotu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTUYLuotu As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTUYLuoja control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTUYLuoja As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTUYSopimusId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTUYSopimusId As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ifpTUYTunnisteyksikkoTyyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYTunnisteyksikkoTyyppiId As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''ddTUYTunnisteyksikkoTyyppiId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddTUYTunnisteyksikkoTyyppiId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ifpTUYTunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYTunnus As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''txtTUYTunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYTunnus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ifpTUYPGTunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYPGTunnus As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''txtTUYPGTunnus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYPGTunnus As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ifpTUYNimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYNimi As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''txtTUYNimi control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYNimi As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''phLaajaNakyma control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phLaajaNakyma As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''ifpTUYPGTunniste control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYPGTunniste As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''txtTUYPGTunniste control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYPGTunniste As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ifpTUYPGKoordinaatti1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYPGKoordinaatti1 As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''ComValTUYPGKoordinaatti1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValTUYPGKoordinaatti1 As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtTUYPGKoordinaatti1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYPGKoordinaatti1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ifpTUYPGKoordinaatti2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYPGKoordinaatti2 As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''ComValTUYPGKoordinaatti2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ComValTUYPGKoordinaatti2 As Global.System.Web.UI.WebControls.CompareValidator

  '''<summary>
  '''txtTUYPGKoordinaatti2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYPGKoordinaatti2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ifpTUYInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifpTUYInfo As Global.appSopimusrekisteri.Infopallura

  '''<summary>
  '''txtTUYInfo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTUYInfo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btTallenna control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btTallenna As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btPeruuta control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btPeruuta As Global.System.Web.UI.WebControls.Button
End Class
