'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace CorporatePaymentsV02

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02"), _
   System.Xml.Serialization.XmlRootAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IsNullable:=False)> _
  Partial Public Class Document

    Private pain00100102Field As pain00100102

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("pain.001.001.02")> _
    Public Property pain00100102() As pain00100102
      Get
        Return Me.pain00100102Field
      End Get
      Set(value As pain00100102)
        Me.pain00100102Field = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute(TypeName:="pain.001.001.02", [Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class pain00100102

    Private grpHdrField As GroupHeader1

    Private pmtInfField() As PaymentInstructionInformation1

    '''<remarks/>
    Public Property GrpHdr() As GroupHeader1
      Get
        Return Me.grpHdrField
      End Get
      Set(value As GroupHeader1)
        Me.grpHdrField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("PmtInf")> _
    Public Property PmtInf() As PaymentInstructionInformation1()
      Get
        Return Me.pmtInfField
      End Get
      Set(value As PaymentInstructionInformation1())
        Me.pmtInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class GroupHeader1

    Private msgIdField As String

    Private creDtTmField As Date

    Private authstnField() As String

    Private btchBookgField As Boolean

    Private btchBookgFieldSpecified As Boolean

    Private nbOfTxsField As String

    Private ctrlSumField As Decimal

    Private ctrlSumFieldSpecified As Boolean

    Private grpgField As Grouping1Code

    Private initgPtyField As PartyIdentification8

    Private fwdgAgtField As BranchAndFinancialInstitutionIdentification3

    '''<remarks/>
    Public Property MsgId() As String
      Get
        Return Me.msgIdField
      End Get
      Set(value As String)
        Me.msgIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CreDtTm() As Date
      Get
        Return Me.creDtTmField
      End Get
      Set(value As Date)
        Me.creDtTmField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Authstn")> _
    Public Property Authstn() As String()
      Get
        Return Me.authstnField
      End Get
      Set(value As String())
        Me.authstnField = value
      End Set
    End Property

    '''<remarks/>
    Public Property BtchBookg() As Boolean
      Get
        Return Me.btchBookgField
      End Get
      Set(value As Boolean)
        Me.btchBookgField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property BtchBookgSpecified() As Boolean
      Get
        Return Me.btchBookgFieldSpecified
      End Get
      Set(value As Boolean)
        Me.btchBookgFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property NbOfTxs() As String
      Get
        Return Me.nbOfTxsField
      End Get
      Set(value As String)
        Me.nbOfTxsField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtrlSum() As Decimal
      Get
        Return Me.ctrlSumField
      End Get
      Set(value As Decimal)
        Me.ctrlSumField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property CtrlSumSpecified() As Boolean
      Get
        Return Me.ctrlSumFieldSpecified
      End Get
      Set(value As Boolean)
        Me.ctrlSumFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property Grpg() As Grouping1Code
      Get
        Return Me.grpgField
      End Get
      Set(value As Grouping1Code)
        Me.grpgField = value
      End Set
    End Property

    '''<remarks/>
    Public Property InitgPty() As PartyIdentification8
      Get
        Return Me.initgPtyField
      End Get
      Set(value As PartyIdentification8)
        Me.initgPtyField = value
      End Set
    End Property

    '''<remarks/>
    Public Property FwdgAgt() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.fwdgAgtField
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.fwdgAgtField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum Grouping1Code

    '''<remarks/>
    SNGL

    '''<remarks/>
    GRPD

    '''<remarks/>
    MIXD
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PartyIdentification8

    Private nmField As String

    Private pstlAdrField As PostalAddress1

    Private idField As Party2Choice

    Private ctryOfResField As String

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PstlAdr() As PostalAddress1
      Get
        Return Me.pstlAdrField
      End Get
      Set(value As PostalAddress1)
        Me.pstlAdrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Id() As Party2Choice
      Get
        Return Me.idField
      End Get
      Set(value As Party2Choice)
        Me.idField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtryOfRes() As String
      Get
        Return Me.ctryOfResField
      End Get
      Set(value As String)
        Me.ctryOfResField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PostalAddress1

    Private adrTpField As AddressType2Code

    Private adrTpFieldSpecified As Boolean

    Private adrLineField() As String

    Private strtNmField As String

    Private bldgNbField As String

    Private pstCdField As String

    Private twnNmField As String

    Private ctrySubDvsnField As String

    Private ctryField As String

    '''<remarks/>
    Public Property AdrTp() As AddressType2Code
      Get
        Return Me.adrTpField
      End Get
      Set(value As AddressType2Code)
        Me.adrTpField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property AdrTpSpecified() As Boolean
      Get
        Return Me.adrTpFieldSpecified
      End Get
      Set(value As Boolean)
        Me.adrTpFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AdrLine")> _
    Public Property AdrLine() As String()
      Get
        Return Me.adrLineField
      End Get
      Set(value As String())
        Me.adrLineField = value
      End Set
    End Property

    '''<remarks/>
    Public Property StrtNm() As String
      Get
        Return Me.strtNmField
      End Get
      Set(value As String)
        Me.strtNmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property BldgNb() As String
      Get
        Return Me.bldgNbField
      End Get
      Set(value As String)
        Me.bldgNbField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PstCd() As String
      Get
        Return Me.pstCdField
      End Get
      Set(value As String)
        Me.pstCdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TwnNm() As String
      Get
        Return Me.twnNmField
      End Get
      Set(value As String)
        Me.twnNmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtrySubDvsn() As String
      Get
        Return Me.ctrySubDvsnField
      End Get
      Set(value As String)
        Me.ctrySubDvsnField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Ctry() As String
      Get
        Return Me.ctryField
      End Get
      Set(value As String)
        Me.ctryField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum AddressType2Code

    '''<remarks/>
    ADDR

    '''<remarks/>
    PBOX

    '''<remarks/>
    HOME

    '''<remarks/>
    BIZZ

    '''<remarks/>
    MLTO

    '''<remarks/>
    DLVY
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CreditorReferenceType1

    Private itemField As Object

    Private issrField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(DocumentType3Code)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Issr() As String
      Get
        Return Me.issrField
      End Get
      Set(value As String)
        Me.issrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum DocumentType3Code

    '''<remarks/>
    RADM

    '''<remarks/>
    RPIN

    '''<remarks/>
    FXDR

    '''<remarks/>
    DISP

    '''<remarks/>
    PUOR

    '''<remarks/>
    SCOR
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CreditorReferenceInformation1

    Private cdtrRefTpField As CreditorReferenceType1

    Private cdtrRefField As String

    '''<remarks/>
    Public Property CdtrRefTp() As CreditorReferenceType1
      Get
        Return Me.cdtrRefTpField
      End Get
      Set(value As CreditorReferenceType1)
        Me.cdtrRefTpField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrRef() As String
      Get
        Return Me.cdtrRefField
      End Get
      Set(value As String)
        Me.cdtrRefField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ReferredDocumentAmount1Choice

    Private itemField As CurrencyAndAmount

    Private itemElementNameField As ItemChoiceType5

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CdtNoteAmt", GetType(CurrencyAndAmount)), _
     System.Xml.Serialization.XmlElementAttribute("DscntApldAmt", GetType(CurrencyAndAmount)), _
     System.Xml.Serialization.XmlElementAttribute("DuePyblAmt", GetType(CurrencyAndAmount)), _
     System.Xml.Serialization.XmlElementAttribute("RmtdAmt", GetType(CurrencyAndAmount)), _
     System.Xml.Serialization.XmlElementAttribute("TaxAmt", GetType(CurrencyAndAmount)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As CurrencyAndAmount
      Get
        Return Me.itemField
      End Get
      Set(value As CurrencyAndAmount)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType5
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType5)
        Me.itemElementNameField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CurrencyAndAmount

    Private ccyField As String

    Private valueField As Decimal

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property Ccy() As String
      Get
        Return Me.ccyField
      End Get
      Set(value As String)
        Me.ccyField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _
    Public Property Value() As Decimal
      Get
        Return Me.valueField
      End Get
      Set(value As Decimal)
        Me.valueField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType5

    '''<remarks/>
    CdtNoteAmt

    '''<remarks/>
    DscntApldAmt

    '''<remarks/>
    DuePyblAmt

    '''<remarks/>
    RmtdAmt

    '''<remarks/>
    TaxAmt
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ReferredDocumentType1

    Private itemField As Object

    Private issrField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(DocumentType2Code)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Issr() As String
      Get
        Return Me.issrField
      End Get
      Set(value As String)
        Me.issrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum DocumentType2Code

    '''<remarks/>
    MSIN

    '''<remarks/>
    CNFA

    '''<remarks/>
    DNFA

    '''<remarks/>
    CINV

    '''<remarks/>
    CREN

    '''<remarks/>
    DEBN

    '''<remarks/>
    HIRI

    '''<remarks/>
    SBIN

    '''<remarks/>
    CMCN

    '''<remarks/>
    SOAC

    '''<remarks/>
    DISP
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ReferredDocumentInformation1

    Private rfrdDocTpField As ReferredDocumentType1

    Private rfrdDocNbField As String

    '''<remarks/>
    Public Property RfrdDocTp() As ReferredDocumentType1
      Get
        Return Me.rfrdDocTpField
      End Get
      Set(value As ReferredDocumentType1)
        Me.rfrdDocTpField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RfrdDocNb() As String
      Get
        Return Me.rfrdDocNbField
      End Get
      Set(value As String)
        Me.rfrdDocNbField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class StructuredRemittanceInformation6

    Private rfrdDocInfField As ReferredDocumentInformation1

    Private rfrdDocRltdDtField As Date

    Private rfrdDocRltdDtFieldSpecified As Boolean

    Private rfrdDocAmtField() As ReferredDocumentAmount1Choice

    Private cdtrRefInfField As CreditorReferenceInformation1

    Private invcrField As PartyIdentification8

    Private invceeField As PartyIdentification8

    Private addtlRmtInfField As String

    '''<remarks/>
    Public Property RfrdDocInf() As ReferredDocumentInformation1
      Get
        Return Me.rfrdDocInfField
      End Get
      Set(value As ReferredDocumentInformation1)
        Me.rfrdDocInfField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property RfrdDocRltdDt() As Date
      Get
        Return Me.rfrdDocRltdDtField
      End Get
      Set(value As Date)
        Me.rfrdDocRltdDtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property RfrdDocRltdDtSpecified() As Boolean
      Get
        Return Me.rfrdDocRltdDtFieldSpecified
      End Get
      Set(value As Boolean)
        Me.rfrdDocRltdDtFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RfrdDocAmt")> _
    Public Property RfrdDocAmt() As ReferredDocumentAmount1Choice()
      Get
        Return Me.rfrdDocAmtField
      End Get
      Set(value As ReferredDocumentAmount1Choice())
        Me.rfrdDocAmtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrRefInf() As CreditorReferenceInformation1
      Get
        Return Me.cdtrRefInfField
      End Get
      Set(value As CreditorReferenceInformation1)
        Me.cdtrRefInfField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Invcr() As PartyIdentification8
      Get
        Return Me.invcrField
      End Get
      Set(value As PartyIdentification8)
        Me.invcrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Invcee() As PartyIdentification8
      Get
        Return Me.invceeField
      End Get
      Set(value As PartyIdentification8)
        Me.invceeField = value
      End Set
    End Property

    '''<remarks/>
    Public Property AddtlRmtInf() As String
      Get
        Return Me.addtlRmtInfField
      End Get
      Set(value As String)
        Me.addtlRmtInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class RemittanceInformation1

    Private ustrdField() As String

    Private strdField() As StructuredRemittanceInformation6

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Ustrd")> _
    Public Property Ustrd() As String()
      Get
        Return Me.ustrdField
      End Get
      Set(value As String())
        Me.ustrdField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Strd")> _
    Public Property Strd() As StructuredRemittanceInformation6()
      Get
        Return Me.strdField
      End Get
      Set(value As StructuredRemittanceInformation6())
        Me.strdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class RemittanceLocation1

    Private rmtIdField As String

    Private rmtLctnMtdField As RemittanceLocationMethod1Code

    Private rmtLctnMtdFieldSpecified As Boolean

    Private rmtLctnElctrncAdrField As String

    Private rmtLctnPstlAdrField As NameAndAddress3

    '''<remarks/>
    Public Property RmtId() As String
      Get
        Return Me.rmtIdField
      End Get
      Set(value As String)
        Me.rmtIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RmtLctnMtd() As RemittanceLocationMethod1Code
      Get
        Return Me.rmtLctnMtdField
      End Get
      Set(value As RemittanceLocationMethod1Code)
        Me.rmtLctnMtdField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property RmtLctnMtdSpecified() As Boolean
      Get
        Return Me.rmtLctnMtdFieldSpecified
      End Get
      Set(value As Boolean)
        Me.rmtLctnMtdFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property RmtLctnElctrncAdr() As String
      Get
        Return Me.rmtLctnElctrncAdrField
      End Get
      Set(value As String)
        Me.rmtLctnElctrncAdrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RmtLctnPstlAdr() As NameAndAddress3
      Get
        Return Me.rmtLctnPstlAdrField
      End Get
      Set(value As NameAndAddress3)
        Me.rmtLctnPstlAdrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum RemittanceLocationMethod1Code

    '''<remarks/>
    FAXI

    '''<remarks/>
    EDIC

    '''<remarks/>
    URID

    '''<remarks/>
    EMAL

    '''<remarks/>
    POST
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class NameAndAddress3

    Private nmField As String

    Private adrField As PostalAddress1

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Adr() As PostalAddress1
      Get
        Return Me.adrField
      End Get
      Set(value As PostalAddress1)
        Me.adrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class TaxType

    Private ctgyDescField As String

    Private rateField As Decimal

    Private rateFieldSpecified As Boolean

    Private taxblBaseAmtField As CurrencyAndAmount

    Private amtField As CurrencyAndAmount

    '''<remarks/>
    Public Property CtgyDesc() As String
      Get
        Return Me.ctgyDescField
      End Get
      Set(value As String)
        Me.ctgyDescField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Rate() As Decimal
      Get
        Return Me.rateField
      End Get
      Set(value As Decimal)
        Me.rateField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property RateSpecified() As Boolean
      Get
        Return Me.rateFieldSpecified
      End Get
      Set(value As Boolean)
        Me.rateFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property TaxblBaseAmt() As CurrencyAndAmount
      Get
        Return Me.taxblBaseAmtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.taxblBaseAmtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Amt() As CurrencyAndAmount
      Get
        Return Me.amtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.amtField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class TaxDetails

    Private certIdField As String

    Private taxTpField As TaxType

    '''<remarks/>
    Public Property CertId() As String
      Get
        Return Me.certIdField
      End Get
      Set(value As String)
        Me.certIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TaxTp() As TaxType
      Get
        Return Me.taxTpField
      End Get
      Set(value As TaxType)
        Me.taxTpField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class TaxInformation2

    Private cdtrTaxIdField As String

    Private cdtrTaxTpField As String

    Private dbtrTaxIdField As String

    Private taxRefNbField As String

    Private ttlTaxblBaseAmtField As CurrencyAndAmount

    Private ttlTaxAmtField As CurrencyAndAmount

    Private taxDtField As Date

    Private taxDtFieldSpecified As Boolean

    Private taxTpInfField() As TaxDetails

    '''<remarks/>
    Public Property CdtrTaxId() As String
      Get
        Return Me.cdtrTaxIdField
      End Get
      Set(value As String)
        Me.cdtrTaxIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrTaxTp() As String
      Get
        Return Me.cdtrTaxTpField
      End Get
      Set(value As String)
        Me.cdtrTaxTpField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DbtrTaxId() As String
      Get
        Return Me.dbtrTaxIdField
      End Get
      Set(value As String)
        Me.dbtrTaxIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TaxRefNb() As String
      Get
        Return Me.taxRefNbField
      End Get
      Set(value As String)
        Me.taxRefNbField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TtlTaxblBaseAmt() As CurrencyAndAmount
      Get
        Return Me.ttlTaxblBaseAmtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.ttlTaxblBaseAmtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TtlTaxAmt() As CurrencyAndAmount
      Get
        Return Me.ttlTaxAmtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.ttlTaxAmtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property TaxDt() As Date
      Get
        Return Me.taxDtField
      End Get
      Set(value As Date)
        Me.taxDtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property TaxDtSpecified() As Boolean
      Get
        Return Me.taxDtFieldSpecified
      End Get
      Set(value As Boolean)
        Me.taxDtFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("TaxTpInf")> _
    Public Property TaxTpInf() As TaxDetails()
      Get
        Return Me.taxTpInfField
      End Get
      Set(value As TaxDetails())
        Me.taxTpInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class StructuredRegulatoryReporting2

    Private cdField As String

    Private amtField As CurrencyAndAmount

    Private infField As String

    '''<remarks/>
    Public Property Cd() As String
      Get
        Return Me.cdField
      End Get
      Set(value As String)
        Me.cdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Amt() As CurrencyAndAmount
      Get
        Return Me.amtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.amtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Inf() As String
      Get
        Return Me.infField
      End Get
      Set(value As String)
        Me.infField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class RegulatoryAuthority

    Private authrtyNmField As String

    Private authrtyCtryField As String

    '''<remarks/>
    Public Property AuthrtyNm() As String
      Get
        Return Me.authrtyNmField
      End Get
      Set(value As String)
        Me.authrtyNmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property AuthrtyCtry() As String
      Get
        Return Me.authrtyCtryField
      End Get
      Set(value As String)
        Me.authrtyCtryField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class RegulatoryReporting2

    Private dbtCdtRptgIndField As RegulatoryReportingType1Code

    Private dbtCdtRptgIndFieldSpecified As Boolean

    Private authrtyField As RegulatoryAuthority

    Private rgltryDtlsField As StructuredRegulatoryReporting2

    '''<remarks/>
    Public Property DbtCdtRptgInd() As RegulatoryReportingType1Code
      Get
        Return Me.dbtCdtRptgIndField
      End Get
      Set(value As RegulatoryReportingType1Code)
        Me.dbtCdtRptgIndField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property DbtCdtRptgIndSpecified() As Boolean
      Get
        Return Me.dbtCdtRptgIndFieldSpecified
      End Get
      Set(value As Boolean)
        Me.dbtCdtRptgIndFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property Authrty() As RegulatoryAuthority
      Get
        Return Me.authrtyField
      End Get
      Set(value As RegulatoryAuthority)
        Me.authrtyField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RgltryDtls() As StructuredRegulatoryReporting2
      Get
        Return Me.rgltryDtlsField
      End Get
      Set(value As StructuredRegulatoryReporting2)
        Me.rgltryDtlsField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum RegulatoryReportingType1Code

    '''<remarks/>
    CRED

    '''<remarks/>
    DEBT

    '''<remarks/>
    BOTH
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class Purpose1Choice

    Private itemField As String

    Private itemElementNameField As ItemChoiceType4

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As String
      Get
        Return Me.itemField
      End Get
      Set(value As String)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType4
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType4)
        Me.itemElementNameField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType4

    '''<remarks/>
    Cd

    '''<remarks/>
    Prtry
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class InstructionForCreditorAgent1

    Private cdField As Instruction3Code

    Private cdFieldSpecified As Boolean

    Private instrInfField As String

    '''<remarks/>
    Public Property Cd() As Instruction3Code
      Get
        Return Me.cdField
      End Get
      Set(value As Instruction3Code)
        Me.cdField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property CdSpecified() As Boolean
      Get
        Return Me.cdFieldSpecified
      End Get
      Set(value As Boolean)
        Me.cdFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property InstrInf() As String
      Get
        Return Me.instrInfField
      End Get
      Set(value As String)
        Me.instrInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum Instruction3Code

    '''<remarks/>
    CHQB

    '''<remarks/>
    HOLD

    '''<remarks/>
    PHOB

    '''<remarks/>
    TELB
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ChequeDeliveryMethod1Choice

    Private itemField As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(ChequeDelivery1Code)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ChequeDelivery1Code

    '''<remarks/>
    MLDB

    '''<remarks/>
    MLCD

    '''<remarks/>
    MLFA

    '''<remarks/>
    CRDB

    '''<remarks/>
    CRCD

    '''<remarks/>
    CRFA

    '''<remarks/>
    PUDB

    '''<remarks/>
    PUCD

    '''<remarks/>
    PUFA

    '''<remarks/>
    RGDB

    '''<remarks/>
    RGCD

    '''<remarks/>
    RGFA
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class Cheque5

    Private chqTpField As ChequeType2Code

    Private chqTpFieldSpecified As Boolean

    Private chqNbField As String

    Private chqFrField As NameAndAddress3

    Private dlvryMtdField As ChequeDeliveryMethod1Choice

    Private dlvrToField As NameAndAddress3

    Private instrPrtyField As Priority2Code

    Private instrPrtyFieldSpecified As Boolean

    Private chqMtrtyDtField As Date

    Private chqMtrtyDtFieldSpecified As Boolean

    Private frmsCdField As String

    Private memoFldField As String

    Private rgnlClrZoneField As String

    Private prtLctnField As String

    '''<remarks/>
    Public Property ChqTp() As ChequeType2Code
      Get
        Return Me.chqTpField
      End Get
      Set(value As ChequeType2Code)
        Me.chqTpField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ChqTpSpecified() As Boolean
      Get
        Return Me.chqTpFieldSpecified
      End Get
      Set(value As Boolean)
        Me.chqTpFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChqNb() As String
      Get
        Return Me.chqNbField
      End Get
      Set(value As String)
        Me.chqNbField = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChqFr() As NameAndAddress3
      Get
        Return Me.chqFrField
      End Get
      Set(value As NameAndAddress3)
        Me.chqFrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DlvryMtd() As ChequeDeliveryMethod1Choice
      Get
        Return Me.dlvryMtdField
      End Get
      Set(value As ChequeDeliveryMethod1Choice)
        Me.dlvryMtdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DlvrTo() As NameAndAddress3
      Get
        Return Me.dlvrToField
      End Get
      Set(value As NameAndAddress3)
        Me.dlvrToField = value
      End Set
    End Property

    '''<remarks/>
    Public Property InstrPrty() As Priority2Code
      Get
        Return Me.instrPrtyField
      End Get
      Set(value As Priority2Code)
        Me.instrPrtyField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property InstrPrtySpecified() As Boolean
      Get
        Return Me.instrPrtyFieldSpecified
      End Get
      Set(value As Boolean)
        Me.instrPrtyFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property ChqMtrtyDt() As Date
      Get
        Return Me.chqMtrtyDtField
      End Get
      Set(value As Date)
        Me.chqMtrtyDtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ChqMtrtyDtSpecified() As Boolean
      Get
        Return Me.chqMtrtyDtFieldSpecified
      End Get
      Set(value As Boolean)
        Me.chqMtrtyDtFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property FrmsCd() As String
      Get
        Return Me.frmsCdField
      End Get
      Set(value As String)
        Me.frmsCdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property MemoFld() As String
      Get
        Return Me.memoFldField
      End Get
      Set(value As String)
        Me.memoFldField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RgnlClrZone() As String
      Get
        Return Me.rgnlClrZoneField
      End Get
      Set(value As String)
        Me.rgnlClrZoneField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PrtLctn() As String
      Get
        Return Me.prtLctnField
      End Get
      Set(value As String)
        Me.prtLctnField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ChequeType2Code

    '''<remarks/>
    CCHQ

    '''<remarks/>
    CCCH

    '''<remarks/>
    BCHQ

    '''<remarks/>
    DRFT

    '''<remarks/>
    ELDR
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum Priority2Code

    '''<remarks/>
    HIGH

    '''<remarks/>
    NORM
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ExchangeRateInformation1

    Private xchgRateField As Decimal

    Private xchgRateFieldSpecified As Boolean

    Private rateTpField As ExchangeRateType1Code

    Private rateTpFieldSpecified As Boolean

    Private ctrctIdField As String

    '''<remarks/>
    Public Property XchgRate() As Decimal
      Get
        Return Me.xchgRateField
      End Get
      Set(value As Decimal)
        Me.xchgRateField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property XchgRateSpecified() As Boolean
      Get
        Return Me.xchgRateFieldSpecified
      End Get
      Set(value As Boolean)
        Me.xchgRateFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property RateTp() As ExchangeRateType1Code
      Get
        Return Me.rateTpField
      End Get
      Set(value As ExchangeRateType1Code)
        Me.rateTpField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property RateTpSpecified() As Boolean
      Get
        Return Me.rateTpFieldSpecified
      End Get
      Set(value As Boolean)
        Me.rateTpFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtrctId() As String
      Get
        Return Me.ctrctIdField
      End Get
      Set(value As String)
        Me.ctrctIdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ExchangeRateType1Code

    '''<remarks/>
    SPOT

    '''<remarks/>
    SALE

    '''<remarks/>
    AGRD
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class EquivalentAmount

    Private amtField As CurrencyAndAmount

    Private ccyOfTrfField As String

    '''<remarks/>
    Public Property Amt() As CurrencyAndAmount
      Get
        Return Me.amtField
      End Get
      Set(value As CurrencyAndAmount)
        Me.amtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CcyOfTrf() As String
      Get
        Return Me.ccyOfTrfField
      End Get
      Set(value As String)
        Me.ccyOfTrfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class AmountType2Choice

    Private itemField As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("EqvtAmt", GetType(EquivalentAmount)), _
     System.Xml.Serialization.XmlElementAttribute("InstdAmt", GetType(CurrencyAndAmount))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PaymentIdentification1

    Private instrIdField As String

    Private endToEndIdField As String

    '''<remarks/>
    Public Property InstrId() As String
      Get
        Return Me.instrIdField
      End Get
      Set(value As String)
        Me.instrIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property EndToEndId() As String
      Get
        Return Me.endToEndIdField
      End Get
      Set(value As String)
        Me.endToEndIdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CreditTransferTransactionInformation1

    Private pmtIdField As PaymentIdentification1

    Private pmtTpInfField As PaymentTypeInformation1

    Private amtField As AmountType2Choice

    Private xchgRateInfField As ExchangeRateInformation1

    Private chrgBrField As ChargeBearerType1Code

    Private chrgBrFieldSpecified As Boolean

    Private chqInstrField As Cheque5

    Private ultmtDbtrField As PartyIdentification8

    Private intrmyAgt1Field As BranchAndFinancialInstitutionIdentification3

    Private intrmyAgt1AcctField As CashAccount7

    Private intrmyAgt2Field As BranchAndFinancialInstitutionIdentification3

    Private intrmyAgt2AcctField As CashAccount7

    Private intrmyAgt3Field As BranchAndFinancialInstitutionIdentification3

    Private intrmyAgt3AcctField As CashAccount7

    Private cdtrAgtField As BranchAndFinancialInstitutionIdentification3

    Private cdtrAgtAcctField As CashAccount7

    Private cdtrField As PartyIdentification8

    Private cdtrAcctField As CashAccount7

    Private ultmtCdtrField As PartyIdentification8

    Private instrForCdtrAgtField() As InstructionForCreditorAgent1

    Private instrForDbtrAgtField As String

    Private purpField As Purpose1Choice

    Private rgltryRptgField() As RegulatoryReporting2

    Private taxField As TaxInformation2

    Private rltdRmtInfField() As RemittanceLocation1

    Private rmtInfField As RemittanceInformation1

    '''<remarks/>
    Public Property PmtId() As PaymentIdentification1
      Get
        Return Me.pmtIdField
      End Get
      Set(value As PaymentIdentification1)
        Me.pmtIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PmtTpInf() As PaymentTypeInformation1
      Get
        Return Me.pmtTpInfField
      End Get
      Set(value As PaymentTypeInformation1)
        Me.pmtTpInfField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Amt() As AmountType2Choice
      Get
        Return Me.amtField
      End Get
      Set(value As AmountType2Choice)
        Me.amtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property XchgRateInf() As ExchangeRateInformation1
      Get
        Return Me.xchgRateInfField
      End Get
      Set(value As ExchangeRateInformation1)
        Me.xchgRateInfField = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChrgBr() As ChargeBearerType1Code
      Get
        Return Me.chrgBrField
      End Get
      Set(value As ChargeBearerType1Code)
        Me.chrgBrField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ChrgBrSpecified() As Boolean
      Get
        Return Me.chrgBrFieldSpecified
      End Get
      Set(value As Boolean)
        Me.chrgBrFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChqInstr() As Cheque5
      Get
        Return Me.chqInstrField
      End Get
      Set(value As Cheque5)
        Me.chqInstrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property UltmtDbtr() As PartyIdentification8
      Get
        Return Me.ultmtDbtrField
      End Get
      Set(value As PartyIdentification8)
        Me.ultmtDbtrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt1() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.intrmyAgt1Field
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.intrmyAgt1Field = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt1Acct() As CashAccount7
      Get
        Return Me.intrmyAgt1AcctField
      End Get
      Set(value As CashAccount7)
        Me.intrmyAgt1AcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt2() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.intrmyAgt2Field
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.intrmyAgt2Field = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt2Acct() As CashAccount7
      Get
        Return Me.intrmyAgt2AcctField
      End Get
      Set(value As CashAccount7)
        Me.intrmyAgt2AcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt3() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.intrmyAgt3Field
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.intrmyAgt3Field = value
      End Set
    End Property

    '''<remarks/>
    Public Property IntrmyAgt3Acct() As CashAccount7
      Get
        Return Me.intrmyAgt3AcctField
      End Get
      Set(value As CashAccount7)
        Me.intrmyAgt3AcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrAgt() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.cdtrAgtField
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.cdtrAgtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrAgtAcct() As CashAccount7
      Get
        Return Me.cdtrAgtAcctField
      End Get
      Set(value As CashAccount7)
        Me.cdtrAgtAcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Cdtr() As PartyIdentification8
      Get
        Return Me.cdtrField
      End Get
      Set(value As PartyIdentification8)
        Me.cdtrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CdtrAcct() As CashAccount7
      Get
        Return Me.cdtrAcctField
      End Get
      Set(value As CashAccount7)
        Me.cdtrAcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property UltmtCdtr() As PartyIdentification8
      Get
        Return Me.ultmtCdtrField
      End Get
      Set(value As PartyIdentification8)
        Me.ultmtCdtrField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("InstrForCdtrAgt")> _
    Public Property InstrForCdtrAgt() As InstructionForCreditorAgent1()
      Get
        Return Me.instrForCdtrAgtField
      End Get
      Set(value As InstructionForCreditorAgent1())
        Me.instrForCdtrAgtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property InstrForDbtrAgt() As String
      Get
        Return Me.instrForDbtrAgtField
      End Get
      Set(value As String)
        Me.instrForDbtrAgtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Purp() As Purpose1Choice
      Get
        Return Me.purpField
      End Get
      Set(value As Purpose1Choice)
        Me.purpField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RgltryRptg")> _
    Public Property RgltryRptg() As RegulatoryReporting2()
      Get
        Return Me.rgltryRptgField
      End Get
      Set(value As RegulatoryReporting2())
        Me.rgltryRptgField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Tax() As TaxInformation2
      Get
        Return Me.taxField
      End Get
      Set(value As TaxInformation2)
        Me.taxField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("RltdRmtInf")> _
    Public Property RltdRmtInf() As RemittanceLocation1()
      Get
        Return Me.rltdRmtInfField
      End Get
      Set(value As RemittanceLocation1())
        Me.rltdRmtInfField = value
      End Set
    End Property

    '''<remarks/>
    Public Property RmtInf() As RemittanceInformation1
      Get
        Return Me.rmtInfField
      End Get
      Set(value As RemittanceInformation1)
        Me.rmtInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PaymentTypeInformation1

    Private instrPrtyField As Priority2Code

    Private instrPrtyFieldSpecified As Boolean

    Private itemField As Object

    Private lclInstrmField As LocalInstrument1Choice

    Private ctgyPurpField As PaymentCategoryPurpose1Code

    Private ctgyPurpFieldSpecified As Boolean

    '''<remarks/>
    Public Property InstrPrty() As Priority2Code
      Get
        Return Me.instrPrtyField
      End Get
      Set(value As Priority2Code)
        Me.instrPrtyField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property InstrPrtySpecified() As Boolean
      Get
        Return Me.instrPrtyFieldSpecified
      End Get
      Set(value As Boolean)
        Me.instrPrtyFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ClrChanl", GetType(ClearingChannel2Code)), _
     System.Xml.Serialization.XmlElementAttribute("SvcLvl", GetType(ServiceLevel2Choice))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    Public Property LclInstrm() As LocalInstrument1Choice
      Get
        Return Me.lclInstrmField
      End Get
      Set(value As LocalInstrument1Choice)
        Me.lclInstrmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtgyPurp() As PaymentCategoryPurpose1Code
      Get
        Return Me.ctgyPurpField
      End Get
      Set(value As PaymentCategoryPurpose1Code)
        Me.ctgyPurpField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property CtgyPurpSpecified() As Boolean
      Get
        Return Me.ctgyPurpFieldSpecified
      End Get
      Set(value As Boolean)
        Me.ctgyPurpFieldSpecified = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ClearingChannel2Code

    '''<remarks/>
    RTGS

    '''<remarks/>
    RTNS

    '''<remarks/>
    MPNS

    '''<remarks/>
    BOOK
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ServiceLevel2Choice

    Private itemField As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(ServiceLevel1Code)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ServiceLevel1Code

    '''<remarks/>
    SEPA

    '''<remarks/>
    SDVA

    '''<remarks/>
    PRPT
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class LocalInstrument1Choice

    Private itemField As String

    Private itemElementNameField As ItemChoiceType2

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As String
      Get
        Return Me.itemField
      End Get
      Set(value As String)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType2
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType2)
        Me.itemElementNameField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType2

    '''<remarks/>
    Cd

    '''<remarks/>
    Prtry
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum PaymentCategoryPurpose1Code

    '''<remarks/>
    CORT

    '''<remarks/>
    SALA

    '''<remarks/>
    TREA

    '''<remarks/>
    CASH

    '''<remarks/>
    DIVI

    '''<remarks/>
    GOVT

    '''<remarks/>
    INTE

    '''<remarks/>
    LOAN

    '''<remarks/>
    PENS

    '''<remarks/>
    SECU

    '''<remarks/>
    SSBE

    '''<remarks/>
    SUPP

    '''<remarks/>
    TAXS

    '''<remarks/>
    TRAD

    '''<remarks/>
    VATX

    '''<remarks/>
    HEDG

    '''<remarks/>
    INTC

    '''<remarks/>
    WHLD
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum ChargeBearerType1Code

    '''<remarks/>
    DEBT

    '''<remarks/>
    CRED

    '''<remarks/>
    SHAR

    '''<remarks/>
    SLEV
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class BranchAndFinancialInstitutionIdentification3

    Private finInstnIdField As FinancialInstitutionIdentification5Choice

    Private brnchIdField As BranchData

    '''<remarks/>
    Public Property FinInstnId() As FinancialInstitutionIdentification5Choice
      Get
        Return Me.finInstnIdField
      End Get
      Set(value As FinancialInstitutionIdentification5Choice)
        Me.finInstnIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property BrnchId() As BranchData
      Get
        Return Me.brnchIdField
      End Get
      Set(value As BranchData)
        Me.brnchIdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class FinancialInstitutionIdentification5Choice

    Private itemField As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("BIC", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("ClrSysMmbId", GetType(ClearingSystemMemberIdentification3Choice)), _
     System.Xml.Serialization.XmlElementAttribute("CmbndId", GetType(FinancialInstitutionIdentification3)), _
     System.Xml.Serialization.XmlElementAttribute("NmAndAdr", GetType(NameAndAddress7)), _
     System.Xml.Serialization.XmlElementAttribute("PrtryId", GetType(GenericIdentification3))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class ClearingSystemMemberIdentification3Choice

    Private itemField As String

    Private itemElementNameField As ItemChoiceType1

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Id", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As String
      Get
        Return Me.itemField
      End Get
      Set(value As String)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType1
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType1)
        Me.itemElementNameField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType1

    '''<remarks/>
    Id

    '''<remarks/>
    Prtry
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class FinancialInstitutionIdentification3

    Private bICField As String

    Private clrSysMmbIdField As ClearingSystemMemberIdentification3Choice

    Private nmField As String

    Private pstlAdrField As PostalAddress1

    Private prtryIdField As GenericIdentification3

    '''<remarks/>
    Public Property BIC() As String
      Get
        Return Me.bICField
      End Get
      Set(value As String)
        Me.bICField = value
      End Set
    End Property

    '''<remarks/>
    Public Property ClrSysMmbId() As ClearingSystemMemberIdentification3Choice
      Get
        Return Me.clrSysMmbIdField
      End Get
      Set(value As ClearingSystemMemberIdentification3Choice)
        Me.clrSysMmbIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PstlAdr() As PostalAddress1
      Get
        Return Me.pstlAdrField
      End Get
      Set(value As PostalAddress1)
        Me.pstlAdrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PrtryId() As GenericIdentification3
      Get
        Return Me.prtryIdField
      End Get
      Set(value As GenericIdentification3)
        Me.prtryIdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class GenericIdentification3

    Private idField As String

    Private issrField As String

    '''<remarks/>
    Public Property Id() As String
      Get
        Return Me.idField
      End Get
      Set(value As String)
        Me.idField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Issr() As String
      Get
        Return Me.issrField
      End Get
      Set(value As String)
        Me.issrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class NameAndAddress7

    Private nmField As String

    Private pstlAdrField As PostalAddress1

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PstlAdr() As PostalAddress1
      Get
        Return Me.pstlAdrField
      End Get
      Set(value As PostalAddress1)
        Me.pstlAdrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class BranchData

    Private idField As String

    Private nmField As String

    Private pstlAdrField As PostalAddress1

    '''<remarks/>
    Public Property Id() As String
      Get
        Return Me.idField
      End Get
      Set(value As String)
        Me.idField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PstlAdr() As PostalAddress1
      Get
        Return Me.pstlAdrField
      End Get
      Set(value As PostalAddress1)
        Me.pstlAdrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CashAccount7

    Private idField As AccountIdentification3Choice

    Private tpField As CashAccountType2

    Private ccyField As String

    Private nmField As String

    '''<remarks/>
    Public Property Id() As AccountIdentification3Choice
      Get
        Return Me.idField
      End Get
      Set(value As AccountIdentification3Choice)
        Me.idField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Tp() As CashAccountType2
      Get
        Return Me.tpField
      End Get
      Set(value As CashAccountType2)
        Me.tpField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Ccy() As String
      Get
        Return Me.ccyField
      End Get
      Set(value As String)
        Me.ccyField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Nm() As String
      Get
        Return Me.nmField
      End Get
      Set(value As String)
        Me.nmField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class AccountIdentification3Choice

    Private itemField As Object

    Private itemElementNameField As ItemChoiceType3

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("BBAN", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("IBAN", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("PrtryAcct", GetType(SimpleIdentificationInformation2)), _
     System.Xml.Serialization.XmlElementAttribute("UPIC", GetType(String)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType3
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType3)
        Me.itemElementNameField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class SimpleIdentificationInformation2

    Private idField As String

    '''<remarks/>
    Public Property Id() As String
      Get
        Return Me.idField
      End Get
      Set(value As String)
        Me.idField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType3

    '''<remarks/>
    BBAN

    '''<remarks/>
    IBAN

    '''<remarks/>
    PrtryAcct

    '''<remarks/>
    UPIC
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class CashAccountType2

    Private itemField As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Cd", GetType(CashAccountType4Code)), _
     System.Xml.Serialization.XmlElementAttribute("Prtry", GetType(String))> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum CashAccountType4Code

    '''<remarks/>
    CASH

    '''<remarks/>
    [CHAR]

    '''<remarks/>
    COMM

    '''<remarks/>
    TAXE

    '''<remarks/>
    CISH

    '''<remarks/>
    TRAS

    '''<remarks/>
    SACC

    '''<remarks/>
    CACC

    '''<remarks/>
    SVGS

    '''<remarks/>
    ONDP

    '''<remarks/>
    MGLD

    '''<remarks/>
    NREX

    '''<remarks/>
    MOMA

    '''<remarks/>
    LOAN

    '''<remarks/>
    SLRY

    '''<remarks/>
    ODFT
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PaymentInstructionInformation1

    Private pmtInfIdField As String

    Private pmtMtdField As PaymentMethod3Code

    Private pmtTpInfField As PaymentTypeInformation1

    Private reqdExctnDtField As Date

    Private poolgAdjstmntDtField As Date

    Private poolgAdjstmntDtFieldSpecified As Boolean

    Private dbtrField As PartyIdentification8

    Private dbtrAcctField As CashAccount7

    Private dbtrAgtField As BranchAndFinancialInstitutionIdentification3

    Private dbtrAgtAcctField As CashAccount7

    Private ultmtDbtrField As PartyIdentification8

    Private chrgBrField As ChargeBearerType1Code

    Private chrgBrFieldSpecified As Boolean

    Private chrgsAcctField As CashAccount7

    Private chrgsAcctAgtField As BranchAndFinancialInstitutionIdentification3

    Private cdtTrfTxInfField() As CreditTransferTransactionInformation1

    '''<remarks/>
    Public Property PmtInfId() As String
      Get
        Return Me.pmtInfIdField
      End Get
      Set(value As String)
        Me.pmtInfIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PmtMtd() As PaymentMethod3Code
      Get
        Return Me.pmtMtdField
      End Get
      Set(value As PaymentMethod3Code)
        Me.pmtMtdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PmtTpInf() As PaymentTypeInformation1
      Get
        Return Me.pmtTpInfField
      End Get
      Set(value As PaymentTypeInformation1)
        Me.pmtTpInfField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property ReqdExctnDt() As Date
      Get
        Return Me.reqdExctnDtField
      End Get
      Set(value As Date)
        Me.reqdExctnDtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property PoolgAdjstmntDt() As Date
      Get
        Return Me.poolgAdjstmntDtField
      End Get
      Set(value As Date)
        Me.poolgAdjstmntDtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property PoolgAdjstmntDtSpecified() As Boolean
      Get
        Return Me.poolgAdjstmntDtFieldSpecified
      End Get
      Set(value As Boolean)
        Me.poolgAdjstmntDtFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property Dbtr() As PartyIdentification8
      Get
        Return Me.dbtrField
      End Get
      Set(value As PartyIdentification8)
        Me.dbtrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DbtrAcct() As CashAccount7
      Get
        Return Me.dbtrAcctField
      End Get
      Set(value As CashAccount7)
        Me.dbtrAcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DbtrAgt() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.dbtrAgtField
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.dbtrAgtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DbtrAgtAcct() As CashAccount7
      Get
        Return Me.dbtrAgtAcctField
      End Get
      Set(value As CashAccount7)
        Me.dbtrAgtAcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property UltmtDbtr() As PartyIdentification8
      Get
        Return Me.ultmtDbtrField
      End Get
      Set(value As PartyIdentification8)
        Me.ultmtDbtrField = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChrgBr() As ChargeBearerType1Code
      Get
        Return Me.chrgBrField
      End Get
      Set(value As ChargeBearerType1Code)
        Me.chrgBrField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ChrgBrSpecified() As Boolean
      Get
        Return Me.chrgBrFieldSpecified
      End Get
      Set(value As Boolean)
        Me.chrgBrFieldSpecified = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChrgsAcct() As CashAccount7
      Get
        Return Me.chrgsAcctField
      End Get
      Set(value As CashAccount7)
        Me.chrgsAcctField = value
      End Set
    End Property

    '''<remarks/>
    Public Property ChrgsAcctAgt() As BranchAndFinancialInstitutionIdentification3
      Get
        Return Me.chrgsAcctAgtField
      End Get
      Set(value As BranchAndFinancialInstitutionIdentification3)
        Me.chrgsAcctAgtField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("CdtTrfTxInf")> _
    Public Property CdtTrfTxInf() As CreditTransferTransactionInformation1()
      Get
        Return Me.cdtTrfTxInfField
      End Get
      Set(value As CreditTransferTransactionInformation1())
        Me.cdtTrfTxInfField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Public Enum PaymentMethod3Code

    '''<remarks/>
    CHK

    '''<remarks/>
    TRF

    '''<remarks/>
    TRA
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class GenericIdentification4

    Private idField As String

    Private idTpField As String

    '''<remarks/>
    Public Property Id() As String
      Get
        Return Me.idField
      End Get
      Set(value As String)
        Me.idField = value
      End Set
    End Property

    '''<remarks/>
    Public Property IdTp() As String
      Get
        Return Me.idTpField
      End Get
      Set(value As String)
        Me.idTpField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class DateAndPlaceOfBirth

    Private birthDtField As Date

    Private prvcOfBirthField As String

    Private cityOfBirthField As String

    Private ctryOfBirthField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")> _
    Public Property BirthDt() As Date
      Get
        Return Me.birthDtField
      End Get
      Set(value As Date)
        Me.birthDtField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PrvcOfBirth() As String
      Get
        Return Me.prvcOfBirthField
      End Get
      Set(value As String)
        Me.prvcOfBirthField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CityOfBirth() As String
      Get
        Return Me.cityOfBirthField
      End Get
      Set(value As String)
        Me.cityOfBirthField = value
      End Set
    End Property

    '''<remarks/>
    Public Property CtryOfBirth() As String
      Get
        Return Me.ctryOfBirthField
      End Get
      Set(value As String)
        Me.ctryOfBirthField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class PersonIdentification3

    Private itemField As Object

    Private itemElementNameField As ItemChoiceType

    Private issrField As String

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AlnRegnNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("CstmrNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("DrvrsLicNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("DtAndPlcOfBirth", GetType(DateAndPlaceOfBirth)), _
     System.Xml.Serialization.XmlElementAttribute("IdntyCardNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("MplyrIdNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("OthrId", GetType(GenericIdentification4)), _
     System.Xml.Serialization.XmlElementAttribute("PsptNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("SclSctyNb", GetType(String)), _
     System.Xml.Serialization.XmlElementAttribute("TaxIdNb", GetType(String)), _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
    Public Property Item() As Object
      Get
        Return Me.itemField
      End Get
      Set(value As Object)
        Me.itemField = value
      End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property ItemElementName() As ItemChoiceType
      Get
        Return Me.itemElementNameField
      End Get
      Set(value As ItemChoiceType)
        Me.itemElementNameField = value
      End Set
    End Property

    '''<remarks/>
    Public Property Issr() As String
      Get
        Return Me.issrField
      End Get
      Set(value As String)
        Me.issrField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02", IncludeInSchema:=False)> _
  Public Enum ItemChoiceType

    '''<remarks/>
    AlnRegnNb

    '''<remarks/>
    CstmrNb

    '''<remarks/>
    DrvrsLicNb

    '''<remarks/>
    DtAndPlcOfBirth

    '''<remarks/>
    IdntyCardNb

    '''<remarks/>
    MplyrIdNb

    '''<remarks/>
    OthrId

    '''<remarks/>
    PsptNb

    '''<remarks/>
    SclSctyNb

    '''<remarks/>
    TaxIdNb
  End Enum

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class OrganisationIdentification2

    Private bICField As String

    Private iBEIField As String

    Private bEIField As String

    Private eANGLNField As String

    Private uSCHUField As String

    Private dUNSField As String

    Private bkPtyIdField As String

    Private taxIdNbField As String

    Private prtryIdField As GenericIdentification3

    '''<remarks/>
    Public Property BIC() As String
      Get
        Return Me.bICField
      End Get
      Set(value As String)
        Me.bICField = value
      End Set
    End Property

    '''<remarks/>
    Public Property IBEI() As String
      Get
        Return Me.iBEIField
      End Get
      Set(value As String)
        Me.iBEIField = value
      End Set
    End Property

    '''<remarks/>
    Public Property BEI() As String
      Get
        Return Me.bEIField
      End Get
      Set(value As String)
        Me.bEIField = value
      End Set
    End Property

    '''<remarks/>
    Public Property EANGLN() As String
      Get
        Return Me.eANGLNField
      End Get
      Set(value As String)
        Me.eANGLNField = value
      End Set
    End Property

    '''<remarks/>
    Public Property USCHU() As String
      Get
        Return Me.uSCHUField
      End Get
      Set(value As String)
        Me.uSCHUField = value
      End Set
    End Property

    '''<remarks/>
    Public Property DUNS() As String
      Get
        Return Me.dUNSField
      End Get
      Set(value As String)
        Me.dUNSField = value
      End Set
    End Property

    '''<remarks/>
    Public Property BkPtyId() As String
      Get
        Return Me.bkPtyIdField
      End Get
      Set(value As String)
        Me.bkPtyIdField = value
      End Set
    End Property

    '''<remarks/>
    Public Property TaxIdNb() As String
      Get
        Return Me.taxIdNbField
      End Get
      Set(value As String)
        Me.taxIdNbField = value
      End Set
    End Property

    '''<remarks/>
    Public Property PrtryId() As GenericIdentification3
      Get
        Return Me.prtryIdField
      End Get
      Set(value As GenericIdentification3)
        Me.prtryIdField = value
      End Set
    End Property
  End Class

  '''<remarks/>
  <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
   System.SerializableAttribute(), _
   System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.ComponentModel.DesignerCategoryAttribute("code"), _
   System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:iso:std:iso:20022:tech:xsd:pain.001.001.02")> _
  Partial Public Class Party2Choice

    Private itemsField() As Object

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("OrgId", GetType(OrganisationIdentification2)), _
     System.Xml.Serialization.XmlElementAttribute("PrvtId", GetType(PersonIdentification3))> _
    Public Property Items() As Object()
      Get
        Return Me.itemsField
      End Get
      Set(value As Object())
        Me.itemsField = value
      End Set
    End Property
  End Class
End Namespace
